from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_atcTextChatPanel(object):
    def setupUi(self, atcTextChatPanel):
        atcTextChatPanel.setObjectName("atcTextChatPanel")
        atcTextChatPanel.resize(349, 284)
        self.verticalLayout = QtWidgets.QVBoxLayout(atcTextChatPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_info = QtWidgets.QLabel(atcTextChatPanel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.channel_info.setFont(font)
        self.channel_info.setObjectName("channel_info")
        self.horizontalLayout_2.addWidget(self.channel_info)
        self.filterSelect_button = QtWidgets.QToolButton(atcTextChatPanel)
        self.filterSelect_button.setObjectName("filterSelect_button")
        self.horizontalLayout_2.addWidget(self.filterSelect_button)
        self.unreadChats_button = QtWidgets.QToolButton(atcTextChatPanel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unreadChats_button.setFont(font)
        self.unreadChats_button.setAutoRaise(True)
        self.unreadChats_button.setObjectName("unreadChats_button")
        self.horizontalLayout_2.addWidget(self.unreadChats_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.chatHistory_view = QtWidgets.QTableView(atcTextChatPanel)
        self.chatHistory_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chatHistory_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.chatHistory_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.chatHistory_view.setShowGrid(False)
        self.chatHistory_view.setObjectName("chatHistory_view")
        self.chatHistory_view.horizontalHeader().setVisible(False)
        self.chatHistory_view.horizontalHeader().setStretchLastSection(True)
        self.chatHistory_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.chatHistory_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msgLine_edit = QtWidgets.QLineEdit(atcTextChatPanel)
        self.msgLine_edit.setObjectName("msgLine_edit")
        self.horizontalLayout.addWidget(self.msgLine_edit)
        self.send_button = QtWidgets.QToolButton(atcTextChatPanel)
        self.send_button.setEnabled(True)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.channel_info.setBuddy(self.filterSelect_button)

        self.retranslateUi(atcTextChatPanel)
        QtCore.QMetaObject.connectSlotsByName(atcTextChatPanel)
        atcTextChatPanel.setTabOrder(self.msgLine_edit, self.send_button)
        atcTextChatPanel.setTabOrder(self.send_button, self.filterSelect_button)
        atcTextChatPanel.setTabOrder(self.filterSelect_button, self.unreadChats_button)
        atcTextChatPanel.setTabOrder(self.unreadChats_button, self.chatHistory_view)

    def retranslateUi(self, atcTextChatPanel):
        _translate = QtCore.QCoreApplication.translate
        atcTextChatPanel.setWindowTitle(_translate("atcTextChatPanel", "ATC text chat"))
        self.channel_info.setText(_translate("atcTextChatPanel", "###"))
        self.filterSelect_button.setText(_translate("atcTextChatPanel", "Select..."))
        self.unreadChats_button.setToolTip(_translate("atcTextChatPanel", "Unread private chats"))
        self.unreadChats_button.setText(_translate("atcTextChatPanel", "##"))
        self.send_button.setText(_translate("atcTextChatPanel", "Send"))

