
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cpdlcConnection(object):
    def setupUi(self, cpdlcConnection):
        cpdlcConnection.setObjectName("cpdlcConnection")
        cpdlcConnection.resize(373, 317)
        self.verticalLayout = QtWidgets.QVBoxLayout(cpdlcConnection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(cpdlcConnection)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(cpdlcConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.status_info = QtWidgets.QLabel(cpdlcConnection)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_info.setFont(font)
        self.status_info.setObjectName("status_info")
        self.gridLayout.addWidget(self.status_info, 1, 1, 1, 2)
        self.resolveProblems_button = QtWidgets.QToolButton(cpdlcConnection)
        self.resolveProblems_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.resolveProblems_button.setObjectName("resolveProblems_button")
        self.gridLayout.addWidget(self.resolveProblems_button, 1, 3, 1, 1)
        self.disconnect_button = QtWidgets.QToolButton(cpdlcConnection)
        self.disconnect_button.setObjectName("disconnect_button")
        self.gridLayout.addWidget(self.disconnect_button, 0, 3, 1, 1)
        self.acftCallsign_info = QtWidgets.QLabel(cpdlcConnection)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.acftCallsign_info.setFont(font)
        self.acftCallsign_info.setObjectName("acftCallsign_info")
        self.gridLayout.addWidget(self.acftCallsign_info, 0, 1, 1, 1)
        self.transfer_button = QtWidgets.QToolButton(cpdlcConnection)
        self.transfer_button.setObjectName("transfer_button")
        self.gridLayout.addWidget(self.transfer_button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.messages_tableView = QtWidgets.QTableView(cpdlcConnection)
        self.messages_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.messages_tableView.setShowGrid(False)
        self.messages_tableView.setObjectName("messages_tableView")
        self.messages_tableView.horizontalHeader().setVisible(False)
        self.messages_tableView.horizontalHeader().setStretchLastSection(True)
        self.messages_tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.messages_tableView)
        self.sendMsg_frame = QtWidgets.QFrame(cpdlcConnection)
        self.sendMsg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendMsg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendMsg_frame.setObjectName("sendMsg_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sendMsg_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ACK_button = QtWidgets.QToolButton(self.sendMsg_frame)
        self.ACK_button.setObjectName("ACK_button")
        self.horizontalLayout.addWidget(self.ACK_button)
        self.reject_button = QtWidgets.QToolButton(self.sendMsg_frame)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout.addWidget(self.reject_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.freeText_edit = QtWidgets.QLineEdit(self.sendMsg_frame)
        self.freeText_edit.setObjectName("freeText_edit")
        self.horizontalLayout_2.addWidget(self.freeText_edit)
        self.sendFreeText_button = QtWidgets.QToolButton(self.sendMsg_frame)
        self.sendFreeText_button.setObjectName("sendFreeText_button")
        self.horizontalLayout_2.addWidget(self.sendFreeText_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.sendMsg_frame)

        self.retranslateUi(cpdlcConnection)
        self.freeText_edit.returnPressed.connect(self.sendFreeText_button.animateClick)
        QtCore.QMetaObject.connectSlotsByName(cpdlcConnection)
        cpdlcConnection.setTabOrder(self.resolveProblems_button, self.messages_tableView)
        cpdlcConnection.setTabOrder(self.messages_tableView, self.ACK_button)
        cpdlcConnection.setTabOrder(self.ACK_button, self.reject_button)
        cpdlcConnection.setTabOrder(self.reject_button, self.freeText_edit)
        cpdlcConnection.setTabOrder(self.freeText_edit, self.sendFreeText_button)
        cpdlcConnection.setTabOrder(self.sendFreeText_button, self.transfer_button)
        cpdlcConnection.setTabOrder(self.transfer_button, self.disconnect_button)

    def retranslateUi(self, cpdlcConnection):
        _translate = QtCore.QCoreApplication.translate
        cpdlcConnection.setWindowTitle(_translate("cpdlcConnection", "Data link window"))
        self.label_3.setText(_translate("cpdlcConnection", "Link status:"))
        self.label.setText(_translate("cpdlcConnection", "ACFT callsign:"))
        self.status_info.setText(_translate("cpdlcConnection", "N/A"))
        self.resolveProblems_button.setToolTip(_translate("cpdlcConnection", "Mark problems resolved"))
        self.resolveProblems_button.setText(_translate("cpdlcConnection", "..."))
        self.disconnect_button.setToolTip(_translate("cpdlcConnection", "Terminate data link"))
        self.disconnect_button.setText(_translate("cpdlcConnection", "X"))
        self.acftCallsign_info.setText(_translate("cpdlcConnection", "N/A"))
        self.transfer_button.setToolTip(_translate("cpdlcConnection", "Transfer data authority"))
        self.transfer_button.setText(_translate("cpdlcConnection", "Transfer..."))
        self.ACK_button.setToolTip(_translate("cpdlcConnection", "Send acknowledgement message, or requested instruction"))
        self.ACK_button.setText(_translate("cpdlcConnection", "ACK"))
        self.reject_button.setText(_translate("cpdlcConnection", "Reject"))
        self.freeText_edit.setPlaceholderText(_translate("cpdlcConnection", "Free text message"))
        self.sendFreeText_button.setText(_translate("cpdlcConnection", "Send"))

