from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_envInfoDialog(object):
    def setupUi(self, envInfoDialog):
        envInfoDialog.setObjectName("envInfoDialog")
        envInfoDialog.resize(526, 407)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(envInfoDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_tabs = QtWidgets.QTabWidget(envInfoDialog)
        self.info_tabs.setObjectName("info_tabs")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.general_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.general_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.radarPosition_infoLabel = QtWidgets.QLabel(self.groupBox_2)
        self.radarPosition_infoLabel.setObjectName("radarPosition_infoLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radarPosition_infoLabel)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.magneticDeclination_infoLabel = QtWidgets.QLabel(self.groupBox_2)
        self.magneticDeclination_infoLabel.setObjectName("magneticDeclination_infoLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.magneticDeclination_infoLabel)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.general_tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rackedStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        self.rackedStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rackedStrips_infoLabel.setObjectName("rackedStrips_infoLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rackedStrips_infoLabel)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.looseStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        self.looseStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.looseStrips_infoLabel.setObjectName("looseStrips_infoLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.looseStrips_infoLabel)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.boxedStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        self.boxedStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.boxedStrips_infoLabel.setObjectName("boxedStrips_infoLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.boxedStrips_infoLabel)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.playingStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.playingStrips_infoLabel.setFont(font)
        self.playingStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playingStrips_infoLabel.setObjectName("playingStrips_infoLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.playingStrips_infoLabel)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.xpdrLinkedStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        self.xpdrLinkedStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xpdrLinkedStrips_infoLabel.setObjectName("xpdrLinkedStrips_infoLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xpdrLinkedStrips_infoLabel)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fplLinkedStrips_infoLabel = QtWidgets.QLabel(self.groupBox)
        self.fplLinkedStrips_infoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fplLinkedStrips_infoLabel.setObjectName("fplLinkedStrips_infoLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fplLinkedStrips_infoLabel)
        self.horizontalLayout.addLayout(self.formLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.info_tabs.addTab(self.general_tab, "")
        self.airport_tab = QtWidgets.QWidget()
        self.airport_tab.setObjectName("airport_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.airport_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.airport_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.airportName_infoLabel = QtWidgets.QLabel(self.groupBox_3)
        self.airportName_infoLabel.setObjectName("airportName_infoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.airportName_infoLabel)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.airportElevation_infoLabel = QtWidgets.QLabel(self.groupBox_3)
        self.airportElevation_infoLabel.setObjectName("airportElevation_infoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.airportElevation_infoLabel)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.airport_tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.runway_tableView = QtWidgets.QTableView(self.groupBox_4)
        self.runway_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.runway_tableView.setObjectName("runway_tableView")
        self.verticalLayout_4.addWidget(self.runway_tableView)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.info_tabs.addTab(self.airport_tab, "")
        self.verticalLayout_2.addWidget(self.info_tabs)
        self.OK_button = QtWidgets.QPushButton(envInfoDialog)
        self.OK_button.setObjectName("OK_button")
        self.verticalLayout_2.addWidget(self.OK_button)

        self.retranslateUi(envInfoDialog)
        self.info_tabs.setCurrentIndex(0)
        self.OK_button.clicked.connect(envInfoDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(envInfoDialog)
        envInfoDialog.setTabOrder(self.info_tabs, self.runway_tableView)
        envInfoDialog.setTabOrder(self.runway_tableView, self.OK_button)

    def retranslateUi(self, envInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        envInfoDialog.setWindowTitle(_translate("envInfoDialog", "Environment information"))
        self.groupBox_2.setTitle(_translate("envInfoDialog", "Location"))
        self.label_11.setText(_translate("envInfoDialog", "Radar position:"))
        self.radarPosition_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label.setText(_translate("envInfoDialog", "Magnetic declination:"))
        self.magneticDeclination_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.groupBox.setTitle(_translate("envInfoDialog", "Current strip count"))
        self.label_6.setText(_translate("envInfoDialog", "Racked:"))
        self.rackedStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_5.setText(_translate("envInfoDialog", "Loose:"))
        self.looseStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_4.setText(_translate("envInfoDialog", "Boxed:"))
        self.boxedStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_9.setText(_translate("envInfoDialog", "Playing total:"))
        self.playingStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_7.setText(_translate("envInfoDialog", "XPDR links:"))
        self.xpdrLinkedStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_8.setText(_translate("envInfoDialog", "FPL links:"))
        self.fplLinkedStrips_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.info_tabs.setTabText(self.info_tabs.indexOf(self.general_tab), _translate("envInfoDialog", "General"))
        self.groupBox_3.setTitle(_translate("envInfoDialog", "General information"))
        self.label_3.setText(_translate("envInfoDialog", "Name:"))
        self.airportName_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.label_2.setText(_translate("envInfoDialog", "Elevation:"))
        self.airportElevation_infoLabel.setText(_translate("envInfoDialog", "##"))
        self.groupBox_4.setTitle(_translate("envInfoDialog", "Runways"))
        self.info_tabs.setTabText(self.info_tabs.indexOf(self.airport_tab), _translate("envInfoDialog", "Base airport"))
        self.OK_button.setText(_translate("envInfoDialog", "OK"))

