from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fplDetailsDialog(object):
    def setupUi(self, fplDetailsDialog):
        fplDetailsDialog.setObjectName("fplDetailsDialog")
        fplDetailsDialog.resize(535, 512)
        self.verticalLayout = QtWidgets.QVBoxLayout(fplDetailsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fplDetails_box = QtWidgets.QGroupBox(fplDetailsDialog)
        self.fplDetails_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fplDetails_box.sizePolicy().hasHeightForWidth())
        self.fplDetails_box.setSizePolicy(sizePolicy)
        self.fplDetails_box.setObjectName("fplDetails_box")
        self.gridLayout = QtWidgets.QGridLayout(self.fplDetails_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.fplDetails_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.depTime_enable = QtWidgets.QCheckBox(self.fplDetails_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depTime_enable.sizePolicy().hasHeightForWidth())
        self.depTime_enable.setSizePolicy(sizePolicy)
        self.depTime_enable.setObjectName("depTime_enable")
        self.horizontalLayout_2.addWidget(self.depTime_enable)
        self.depTime_edit = QtWidgets.QDateTimeEdit(self.fplDetails_box)
        self.depTime_edit.setEnabled(False)
        self.depTime_edit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.depTime_edit.setCalendarPopup(False)
        self.depTime_edit.setCurrentSectionIndex(3)
        self.depTime_edit.setTimeSpec(QtCore.Qt.UTC)
        self.depTime_edit.setObjectName("depTime_edit")
        self.horizontalLayout_2.addWidget(self.depTime_edit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 3, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.soulsOnBoard_enable = QtWidgets.QCheckBox(self.fplDetails_box)
        self.soulsOnBoard_enable.setObjectName("soulsOnBoard_enable")
        self.horizontalLayout_6.addWidget(self.soulsOnBoard_enable)
        self.soulsOnBoard_edit = QtWidgets.QSpinBox(self.fplDetails_box)
        self.soulsOnBoard_edit.setEnabled(False)
        self.soulsOnBoard_edit.setMinimum(1)
        self.soulsOnBoard_edit.setMaximum(999)
        self.soulsOnBoard_edit.setObjectName("soulsOnBoard_edit")
        self.horizontalLayout_6.addWidget(self.soulsOnBoard_edit)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 3, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.fplDetails_box)
        self.label_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fplDetails_box)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.altAirportPicker_widget = AirportPicker(self.fplDetails_box)
        self.altAirportPicker_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.altAirportPicker_widget.setObjectName("altAirportPicker_widget")
        self.gridLayout.addWidget(self.altAirportPicker_widget, 6, 1, 1, 1)
        self.arrAirportPicker_widget = AirportPicker(self.fplDetails_box)
        self.arrAirportPicker_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.arrAirportPicker_widget.setObjectName("arrAirportPicker_widget")
        self.gridLayout.addWidget(self.arrAirportPicker_widget, 3, 1, 1, 1)
        self.departure_label = QtWidgets.QLabel(self.fplDetails_box)
        self.departure_label.setObjectName("departure_label")
        self.gridLayout.addWidget(self.departure_label, 2, 0, 1, 1)
        self.route_edit = RouteEditWidget(self.fplDetails_box)
        self.route_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.route_edit.setObjectName("route_edit")
        self.gridLayout.addWidget(self.route_edit, 4, 1, 1, 5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.EET_enable = QtWidgets.QCheckBox(self.fplDetails_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EET_enable.sizePolicy().hasHeightForWidth())
        self.EET_enable.setSizePolicy(sizePolicy)
        self.EET_enable.setObjectName("EET_enable")
        self.horizontalLayout_3.addWidget(self.EET_enable)
        self.EETh_edit = QtWidgets.QSpinBox(self.fplDetails_box)
        self.EETh_edit.setEnabled(False)
        self.EETh_edit.setProperty("value", 1)
        self.EETh_edit.setObjectName("EETh_edit")
        self.horizontalLayout_3.addWidget(self.EETh_edit)
        self.EETmin_edit = QtWidgets.QSpinBox(self.fplDetails_box)
        self.EETmin_edit.setEnabled(False)
        self.EETmin_edit.setMaximum(59)
        self.EETmin_edit.setObjectName("EETmin_edit")
        self.horizontalLayout_3.addWidget(self.EETmin_edit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 3, 1, 3)
        self.arrival_label = QtWidgets.QLabel(self.fplDetails_box)
        self.arrival_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_label.sizePolicy().hasHeightForWidth())
        self.arrival_label.setSizePolicy(sizePolicy)
        self.arrival_label.setObjectName("arrival_label")
        self.gridLayout.addWidget(self.arrival_label, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TAS_enable = QtWidgets.QCheckBox(self.fplDetails_box)
        self.TAS_enable.setObjectName("TAS_enable")
        self.horizontalLayout_5.addWidget(self.TAS_enable)
        self.TAS_edit = QtWidgets.QSpinBox(self.fplDetails_box)
        self.TAS_edit.setEnabled(False)
        self.TAS_edit.setMinimum(50)
        self.TAS_edit.setMaximum(999)
        self.TAS_edit.setSingleStep(10)
        self.TAS_edit.setProperty("value", 250)
        self.TAS_edit.setObjectName("TAS_edit")
        self.horizontalLayout_5.addWidget(self.TAS_edit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 3, 1, 3)
        self.aircraftType_edit = AircraftTypeCombo(self.fplDetails_box)
        self.aircraftType_edit.setEditable(True)
        self.aircraftType_edit.setObjectName("aircraftType_edit")
        self.gridLayout.addWidget(self.aircraftType_edit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fplDetails_box)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.fplDetails_box)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.depAirportPicker_widget = AirportPicker(self.fplDetails_box)
        self.depAirportPicker_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.depAirportPicker_widget.setObjectName("depAirportPicker_widget")
        self.gridLayout.addWidget(self.depAirportPicker_widget, 2, 1, 1, 1)
        self.comments_edit = QtWidgets.QPlainTextEdit(self.fplDetails_box)
        self.comments_edit.setTabChangesFocus(True)
        self.comments_edit.setObjectName("comments_edit")
        self.gridLayout.addWidget(self.comments_edit, 8, 1, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.fplDetails_box)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.callsign_edit = QtWidgets.QLineEdit(self.fplDetails_box)
        self.callsign_edit.setObjectName("callsign_edit")
        self.gridLayout.addWidget(self.callsign_edit, 0, 1, 1, 1)
        self.cruiseAlt_edit = QtWidgets.QLineEdit(self.fplDetails_box)
        self.cruiseAlt_edit.setObjectName("cruiseAlt_edit")
        self.gridLayout.addWidget(self.cruiseAlt_edit, 5, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.fplDetails_box)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 0, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.fplDetails_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.flightRules_select = QtWidgets.QComboBox(self.fplDetails_box)
        self.flightRules_select.setObjectName("flightRules_select")
        self.flightRules_select.addItem("")
        self.flightRules_select.setItemText(0, "")
        self.flightRules_select.addItem("")
        self.flightRules_select.addItem("")
        self.gridLayout.addWidget(self.flightRules_select, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.fplDetails_box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.wakeTurbCat_select = QtWidgets.QComboBox(self.fplDetails_box)
        self.wakeTurbCat_select.setObjectName("wakeTurbCat_select")
        self.wakeTurbCat_select.addItem("")
        self.wakeTurbCat_select.setItemText(0, "")
        self.wakeTurbCat_select.addItem("")
        self.wakeTurbCat_select.addItem("")
        self.wakeTurbCat_select.addItem("")
        self.wakeTurbCat_select.addItem("")
        self.gridLayout.addWidget(self.wakeTurbCat_select, 1, 4, 1, 1)
        self.autoFillWTC_button = QtWidgets.QToolButton(self.fplDetails_box)
        self.autoFillWTC_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.autoFillWTC_button.setCheckable(True)
        self.autoFillWTC_button.setChecked(True)
        self.autoFillWTC_button.setObjectName("autoFillWTC_button")
        self.gridLayout.addWidget(self.autoFillWTC_button, 1, 2, 1, 1)
        self.label_5.raise_()
        self.callsign_edit.raise_()
        self.label_2.raise_()
        self.aircraftType_edit.raise_()
        self.departure_label.raise_()
        self.arrival_label.raise_()
        self.label_8.raise_()
        self.comments_edit.raise_()
        self.label_14.raise_()
        self.line_2.raise_()
        self.label_4.raise_()
        self.cruiseAlt_edit.raise_()
        self.depAirportPicker_widget.raise_()
        self.arrAirportPicker_widget.raise_()
        self.label_3.raise_()
        self.altAirportPicker_widget.raise_()
        self.route_edit.raise_()
        self.label_9.raise_()
        self.flightRules_select.raise_()
        self.label.raise_()
        self.wakeTurbCat_select.raise_()
        self.autoFillWTC_button.raise_()
        self.verticalLayout.addWidget(self.fplDetails_box)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.onlineStatus_frame = QtWidgets.QFrame(fplDetailsDialog)
        self.onlineStatus_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onlineStatus_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onlineStatus_frame.setObjectName("onlineStatus_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.onlineStatus_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.onlineStatus_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.onlineStatus_infoLabel = QtWidgets.QLabel(self.onlineStatus_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.onlineStatus_infoLabel.setFont(font)
        self.onlineStatus_infoLabel.setObjectName("onlineStatus_infoLabel")
        self.gridLayout_2.addWidget(self.onlineStatus_infoLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.openFPL_button = QtWidgets.QToolButton(self.onlineStatus_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFPL_button.sizePolicy().hasHeightForWidth())
        self.openFPL_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openFPL_button.setFont(font)
        self.openFPL_button.setObjectName("openFPL_button")
        self.gridLayout_2.addWidget(self.openFPL_button, 0, 4, 1, 1)
        self.closeFPL_button = QtWidgets.QToolButton(self.onlineStatus_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeFPL_button.sizePolicy().hasHeightForWidth())
        self.closeFPL_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeFPL_button.setFont(font)
        self.closeFPL_button.setObjectName("closeFPL_button")
        self.gridLayout_2.addWidget(self.closeFPL_button, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.onlineStatus_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.publishOnlineOnSave_tickBox = QtWidgets.QCheckBox(self.onlineStatus_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publishOnlineOnSave_tickBox.sizePolicy().hasHeightForWidth())
        self.publishOnlineOnSave_tickBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publishOnlineOnSave_tickBox.setFont(font)
        self.publishOnlineOnSave_tickBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.publishOnlineOnSave_tickBox.setCheckable(True)
        self.publishOnlineOnSave_tickBox.setChecked(False)
        self.publishOnlineOnSave_tickBox.setObjectName("publishOnlineOnSave_tickBox")
        self.gridLayout_2.addWidget(self.publishOnlineOnSave_tickBox, 1, 4, 1, 2)
        self.viewOnlineComments_button = QtWidgets.QToolButton(self.onlineStatus_frame)
        self.viewOnlineComments_button.setObjectName("viewOnlineComments_button")
        self.gridLayout_2.addWidget(self.viewOnlineComments_button, 0, 2, 1, 1)
        self.syncStatus_infoLabel = QtWidgets.QLabel(self.onlineStatus_frame)
        self.syncStatus_infoLabel.setObjectName("syncStatus_infoLabel")
        self.gridLayout_2.addWidget(self.syncStatus_infoLabel, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.onlineStatus_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(fplDetailsDialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.stripLinked_info = QtWidgets.QLabel(fplDetailsDialog)
        self.stripLinked_info.setObjectName("stripLinked_info")
        self.horizontalLayout.addWidget(self.stripLinked_info)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancel_button = QtWidgets.QPushButton(fplDetailsDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.save_button = QtWidgets.QPushButton(fplDetailsDialog)
        self.save_button.setDefault(True)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_8.setBuddy(self.comments_edit)
        self.label_5.setBuddy(self.callsign_edit)
        self.label_4.setBuddy(self.cruiseAlt_edit)
        self.departure_label.setBuddy(self.depAirportPicker_widget)
        self.arrival_label.setBuddy(self.arrAirportPicker_widget)
        self.label_2.setBuddy(self.aircraftType_edit)
        self.label_14.setBuddy(self.route_edit)
        self.label_3.setBuddy(self.altAirportPicker_widget)
        self.label_9.setBuddy(self.flightRules_select)
        self.label.setBuddy(self.wakeTurbCat_select)

        self.retranslateUi(fplDetailsDialog)
        self.depTime_enable.toggled['bool'].connect(self.depTime_edit.setEnabled)
        self.soulsOnBoard_enable.toggled['bool'].connect(self.soulsOnBoard_edit.setEnabled)
        self.TAS_enable.toggled['bool'].connect(self.TAS_edit.setEnabled)
        self.cancel_button.clicked.connect(fplDetailsDialog.reject)
        self.EET_enable.toggled['bool'].connect(self.EETh_edit.setEnabled)
        self.EET_enable.toggled['bool'].connect(self.EETmin_edit.setEnabled)
        self.depTime_enable.toggled['bool'].connect(self.depTime_edit.setFocus)
        self.EET_enable.toggled['bool'].connect(self.EETh_edit.setFocus)
        self.soulsOnBoard_enable.toggled['bool'].connect(self.soulsOnBoard_edit.setFocus)
        self.TAS_enable.toggled['bool'].connect(self.TAS_edit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(fplDetailsDialog)
        fplDetailsDialog.setTabOrder(self.callsign_edit, self.aircraftType_edit)
        fplDetailsDialog.setTabOrder(self.aircraftType_edit, self.depAirportPicker_widget)
        fplDetailsDialog.setTabOrder(self.depAirportPicker_widget, self.arrAirportPicker_widget)
        fplDetailsDialog.setTabOrder(self.arrAirportPicker_widget, self.route_edit)
        fplDetailsDialog.setTabOrder(self.route_edit, self.cruiseAlt_edit)
        fplDetailsDialog.setTabOrder(self.cruiseAlt_edit, self.altAirportPicker_widget)
        fplDetailsDialog.setTabOrder(self.altAirportPicker_widget, self.flightRules_select)
        fplDetailsDialog.setTabOrder(self.flightRules_select, self.wakeTurbCat_select)
        fplDetailsDialog.setTabOrder(self.wakeTurbCat_select, self.depTime_enable)
        fplDetailsDialog.setTabOrder(self.depTime_enable, self.depTime_edit)
        fplDetailsDialog.setTabOrder(self.depTime_edit, self.EET_enable)
        fplDetailsDialog.setTabOrder(self.EET_enable, self.EETh_edit)
        fplDetailsDialog.setTabOrder(self.EETh_edit, self.EETmin_edit)
        fplDetailsDialog.setTabOrder(self.EETmin_edit, self.TAS_enable)
        fplDetailsDialog.setTabOrder(self.TAS_enable, self.TAS_edit)
        fplDetailsDialog.setTabOrder(self.TAS_edit, self.soulsOnBoard_enable)
        fplDetailsDialog.setTabOrder(self.soulsOnBoard_enable, self.soulsOnBoard_edit)
        fplDetailsDialog.setTabOrder(self.soulsOnBoard_edit, self.comments_edit)
        fplDetailsDialog.setTabOrder(self.comments_edit, self.viewOnlineComments_button)
        fplDetailsDialog.setTabOrder(self.viewOnlineComments_button, self.openFPL_button)
        fplDetailsDialog.setTabOrder(self.openFPL_button, self.closeFPL_button)
        fplDetailsDialog.setTabOrder(self.closeFPL_button, self.publishOnlineOnSave_tickBox)
        fplDetailsDialog.setTabOrder(self.publishOnlineOnSave_tickBox, self.save_button)
        fplDetailsDialog.setTabOrder(self.save_button, self.cancel_button)

    def retranslateUi(self, fplDetailsDialog):
        _translate = QtCore.QCoreApplication.translate
        fplDetailsDialog.setWindowTitle(_translate("fplDetailsDialog", "Flight plan details"))
        self.fplDetails_box.setTitle(_translate("fplDetailsDialog", "Local FPL copy"))
        self.label_8.setText(_translate("fplDetailsDialog", "ATC comment:"))
        self.depTime_enable.setText(_translate("fplDetailsDialog", "UTC"))
        self.depTime_edit.setDisplayFormat(_translate("fplDetailsDialog", "dd/MM/yyyy, HH:mm"))
        self.soulsOnBoard_enable.setText(_translate("fplDetailsDialog", "Souls on board:"))
        self.label_5.setText(_translate("fplDetailsDialog", "Callsign:"))
        self.label_4.setText(_translate("fplDetailsDialog", "Cruise alt./FL:"))
        self.departure_label.setText(_translate("fplDetailsDialog", "Departure:"))
        self.EET_enable.setText(_translate("fplDetailsDialog", "EET"))
        self.EETh_edit.setSuffix(_translate("fplDetailsDialog", " h"))
        self.EETmin_edit.setSuffix(_translate("fplDetailsDialog", " min"))
        self.arrival_label.setText(_translate("fplDetailsDialog", "Arrival:"))
        self.TAS_enable.setText(_translate("fplDetailsDialog", "TAS:"))
        self.TAS_edit.setSuffix(_translate("fplDetailsDialog", " kt"))
        self.label_2.setText(_translate("fplDetailsDialog", "Aircraft type:"))
        self.label_14.setText(_translate("fplDetailsDialog", "Route:"))
        self.label_3.setText(_translate("fplDetailsDialog", "Alt. dest.:"))
        self.label_9.setText(_translate("fplDetailsDialog", "Rules:"))
        self.flightRules_select.setItemText(1, _translate("fplDetailsDialog", "IFR"))
        self.flightRules_select.setItemText(2, _translate("fplDetailsDialog", "VFR"))
        self.label.setText(_translate("fplDetailsDialog", "WTC:"))
        self.wakeTurbCat_select.setItemText(1, _translate("fplDetailsDialog", "L"))
        self.wakeTurbCat_select.setItemText(2, _translate("fplDetailsDialog", "M"))
        self.wakeTurbCat_select.setItemText(3, _translate("fplDetailsDialog", "H"))
        self.wakeTurbCat_select.setItemText(4, _translate("fplDetailsDialog", "J"))
        self.autoFillWTC_button.setToolTip(_translate("fplDetailsDialog", "WTC auto-fill with type change"))
        self.autoFillWTC_button.setText(_translate("fplDetailsDialog", ">>"))
        self.label_6.setText(_translate("fplDetailsDialog", "Online status:"))
        self.onlineStatus_infoLabel.setText(_translate("fplDetailsDialog", "##"))
        self.openFPL_button.setText(_translate("fplDetailsDialog", "OPEN"))
        self.closeFPL_button.setText(_translate("fplDetailsDialog", "CLOSE"))
        self.label_7.setText(_translate("fplDetailsDialog", "Local changes:"))
        self.publishOnlineOnSave_tickBox.setToolTip(_translate("fplDetailsDialog", "Push FPL or local changes online"))
        self.publishOnlineOnSave_tickBox.setText(_translate("fplDetailsDialog", "Publish online"))
        self.viewOnlineComments_button.setText(_translate("fplDetailsDialog", "View\n"
"comments"))
        self.syncStatus_infoLabel.setText(_translate("fplDetailsDialog", "##"))
        self.label_10.setText(_translate("fplDetailsDialog", "Strip linked:"))
        self.stripLinked_info.setText(_translate("fplDetailsDialog", "##"))
        self.cancel_button.setText(_translate("fplDetailsDialog", "Cancel"))
        self.save_button.setText(_translate("fplDetailsDialog", "OK"))

from gui.widgets.basicWidgets import AircraftTypeCombo
from gui.widgets.miscWidgets import AirportPicker
from gui.widgets.routeWidgets import RouteEditWidget
