from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_localSettingsDialog(object):
    def setupUi(self, localSettingsDialog):
        localSettingsDialog.setObjectName("localSettingsDialog")
        localSettingsDialog.resize(637, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(localSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_tabs = QtWidgets.QTabWidget(localSettingsDialog)
        self.settings_tabs.setObjectName("settings_tabs")
        self.radar_tab = QtWidgets.QWidget()
        self.radar_tab.setObjectName("radar_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.radar_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.radar_tab)
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayout_11 = QtWidgets.QFormLayout(self.groupBox_12)
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        self.label_26.setObjectName("label_26")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.radarHorizontalRange_edit = QtWidgets.QSpinBox(self.groupBox_12)
        self.radarHorizontalRange_edit.setAccelerated(True)
        self.radarHorizontalRange_edit.setMinimum(20)
        self.radarHorizontalRange_edit.setMaximum(1000)
        self.radarHorizontalRange_edit.setProperty("value", 100)
        self.radarHorizontalRange_edit.setObjectName("radarHorizontalRange_edit")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radarHorizontalRange_edit)
        self.label_25 = QtWidgets.QLabel(self.groupBox_12)
        self.label_25.setObjectName("label_25")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.radarFloor_edit = QtWidgets.QSpinBox(self.groupBox_12)
        self.radarFloor_edit.setMaximum(5000)
        self.radarFloor_edit.setSingleStep(100)
        self.radarFloor_edit.setObjectName("radarFloor_edit")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radarFloor_edit)
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setObjectName("label_24")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.capability_noSSR_radioButton = QtWidgets.QRadioButton(self.groupBox_12)
        self.capability_noSSR_radioButton.setObjectName("capability_noSSR_radioButton")
        self.horizontalLayout_4.addWidget(self.capability_noSSR_radioButton)
        self.capability_modeA_radioButton = QtWidgets.QRadioButton(self.groupBox_12)
        self.capability_modeA_radioButton.setObjectName("capability_modeA_radioButton")
        self.horizontalLayout_4.addWidget(self.capability_modeA_radioButton)
        self.capability_modeC_radioButton = QtWidgets.QRadioButton(self.groupBox_12)
        self.capability_modeC_radioButton.setObjectName("capability_modeC_radioButton")
        self.horizontalLayout_4.addWidget(self.capability_modeC_radioButton)
        self.capability_modeS_radioButton = QtWidgets.QRadioButton(self.groupBox_12)
        self.capability_modeS_radioButton.setObjectName("capability_modeS_radioButton")
        self.horizontalLayout_4.addWidget(self.capability_modeS_radioButton)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_27 = QtWidgets.QLabel(self.groupBox_12)
        self.label_27.setObjectName("label_27")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.radarUpdateInterval_edit = QtWidgets.QSpinBox(self.groupBox_12)
        self.radarUpdateInterval_edit.setEnabled(True)
        self.radarUpdateInterval_edit.setMinimum(1)
        self.radarUpdateInterval_edit.setMaximum(60)
        self.radarUpdateInterval_edit.setProperty("value", 2)
        self.radarUpdateInterval_edit.setObjectName("radarUpdateInterval_edit")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radarUpdateInterval_edit)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.groupBox = QtWidgets.QGroupBox(self.radar_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioDirectionFinding_tickBox = QtWidgets.QCheckBox(self.groupBox)
        self.radioDirectionFinding_tickBox.setObjectName("radioDirectionFinding_tickBox")
        self.verticalLayout_7.addWidget(self.radioDirectionFinding_tickBox)
        self.cpdlc_tickBox = QtWidgets.QCheckBox(self.groupBox)
        self.cpdlc_tickBox.setObjectName("cpdlc_tickBox")
        self.verticalLayout_7.addWidget(self.cpdlc_tickBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.stripPrinter_groupBox = QtWidgets.QGroupBox(self.radar_tab)
        self.stripPrinter_groupBox.setObjectName("stripPrinter_groupBox")
        self.formLayout_6 = QtWidgets.QFormLayout(self.stripPrinter_groupBox)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_14 = QtWidgets.QLabel(self.stripPrinter_groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stripAutoPrint_DEP_tickBox = QtWidgets.QCheckBox(self.stripPrinter_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripAutoPrint_DEP_tickBox.sizePolicy().hasHeightForWidth())
        self.stripAutoPrint_DEP_tickBox.setSizePolicy(sizePolicy)
        self.stripAutoPrint_DEP_tickBox.setObjectName("stripAutoPrint_DEP_tickBox")
        self.horizontalLayout_2.addWidget(self.stripAutoPrint_DEP_tickBox)
        self.stripAutoPrint_ARR_tickBox = QtWidgets.QCheckBox(self.stripPrinter_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripAutoPrint_ARR_tickBox.sizePolicy().hasHeightForWidth())
        self.stripAutoPrint_ARR_tickBox.setSizePolicy(sizePolicy)
        self.stripAutoPrint_ARR_tickBox.setObjectName("stripAutoPrint_ARR_tickBox")
        self.horizontalLayout_2.addWidget(self.stripAutoPrint_ARR_tickBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stripAutoPrint_ifrOnly_tickBox = QtWidgets.QCheckBox(self.stripPrinter_groupBox)
        self.stripAutoPrint_ifrOnly_tickBox.setObjectName("stripAutoPrint_ifrOnly_tickBox")
        self.horizontalLayout_2.addWidget(self.stripAutoPrint_ifrOnly_tickBox)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.stripAutoPrint_leadTime_edit = QtWidgets.QSpinBox(self.stripPrinter_groupBox)
        self.stripAutoPrint_leadTime_edit.setMaximum(60)
        self.stripAutoPrint_leadTime_edit.setObjectName("stripAutoPrint_leadTime_edit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stripAutoPrint_leadTime_edit)
        self.label_40 = QtWidgets.QLabel(self.stripPrinter_groupBox)
        self.label_40.setObjectName("label_40")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.verticalLayout_2.addWidget(self.stripPrinter_groupBox)
        self.settings_tabs.addTab(self.radar_tab, "")
        self.rules_tab = QtWidgets.QWidget()
        self.rules_tab.setObjectName("rules_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rules_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.rules_tab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_13.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        self.label_21.setObjectName("label_21")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.horizontalSeparation_edit = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.horizontalSeparation_edit.setDecimals(1)
        self.horizontalSeparation_edit.setMinimum(1.0)
        self.horizontalSeparation_edit.setMaximum(20.0)
        self.horizontalSeparation_edit.setSingleStep(0.1)
        self.horizontalSeparation_edit.setObjectName("horizontalSeparation_edit")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSeparation_edit)
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        self.label_22.setObjectName("label_22")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.verticalSeparation_edit = QtWidgets.QSpinBox(self.groupBox_11)
        self.verticalSeparation_edit.setMinimum(100)
        self.verticalSeparation_edit.setMaximum(1000)
        self.verticalSeparation_edit.setSingleStep(100)
        self.verticalSeparation_edit.setProperty("value", 500)
        self.verticalSeparation_edit.setObjectName("verticalSeparation_edit")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.verticalSeparation_edit)
        self.label_23 = QtWidgets.QLabel(self.groupBox_11)
        self.label_23.setObjectName("label_23")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.conflictWarningFloorFL_edit = QtWidgets.QSpinBox(self.groupBox_11)
        self.conflictWarningFloorFL_edit.setMinimum(20)
        self.conflictWarningFloorFL_edit.setMaximum(300)
        self.conflictWarningFloorFL_edit.setSingleStep(10)
        self.conflictWarningFloorFL_edit.setProperty("value", 100)
        self.conflictWarningFloorFL_edit.setObjectName("conflictWarningFloorFL_edit")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.conflictWarningFloorFL_edit)
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.groupBox_2 = QtWidgets.QGroupBox(self.rules_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.transitionAltitude_edit = QtWidgets.QSpinBox(self.groupBox_2)
        self.transitionAltitude_edit.setMinimum(1000)
        self.transitionAltitude_edit.setMaximum(20000)
        self.transitionAltitude_edit.setSingleStep(1000)
        self.transitionAltitude_edit.setObjectName("transitionAltitude_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transitionAltitude_edit)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.uncontrolledVFRcode_edit = XpdrCodeSpinBox(self.groupBox_2)
        self.uncontrolledVFRcode_edit.setObjectName("uncontrolledVFRcode_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uncontrolledVFRcode_edit)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.radioName_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.radioName_edit.setObjectName("radioName_edit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radioName_edit)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.settings_tabs.addTab(self.rules_tab, "")
        self.xpdrRanges_tab = QtWidgets.QWidget()
        self.xpdrRanges_tab.setObjectName("xpdrRanges_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.xpdrRanges_tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.range3_groupBox = QtWidgets.QGroupBox(self.xpdrRanges_tab)
        self.range3_groupBox.setCheckable(True)
        self.range3_groupBox.setChecked(False)
        self.range3_groupBox.setObjectName("range3_groupBox")
        self.formLayout_9 = QtWidgets.QFormLayout(self.range3_groupBox)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_7 = QtWidgets.QLabel(self.range3_groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.range3_name_edit = QtWidgets.QLineEdit(self.range3_groupBox)
        self.range3_name_edit.setObjectName("range3_name_edit")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.range3_name_edit)
        self.label_9 = QtWidgets.QLabel(self.range3_groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.range3_lo_edit = XpdrCodeSpinBox(self.range3_groupBox)
        self.range3_lo_edit.setObjectName("range3_lo_edit")
        self.horizontalLayout_6.addWidget(self.range3_lo_edit)
        self.label_8 = QtWidgets.QLabel(self.range3_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.range3_hi_edit = XpdrCodeSpinBox(self.range3_groupBox)
        self.range3_hi_edit.setObjectName("range3_hi_edit")
        self.horizontalLayout_6.addWidget(self.range3_hi_edit)
        self.formLayout_9.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_19 = QtWidgets.QLabel(self.range3_groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.range3_colourPicker = ColourPicker(self.range3_groupBox)
        self.range3_colourPicker.setObjectName("range3_colourPicker")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.range3_colourPicker)
        self.gridLayout.addWidget(self.range3_groupBox, 1, 2, 1, 1)
        self.range4_groupBox = QtWidgets.QGroupBox(self.xpdrRanges_tab)
        self.range4_groupBox.setCheckable(True)
        self.range4_groupBox.setChecked(False)
        self.range4_groupBox.setObjectName("range4_groupBox")
        self.formLayout_10 = QtWidgets.QFormLayout(self.range4_groupBox)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_10 = QtWidgets.QLabel(self.range4_groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.range4_name_edit = QtWidgets.QLineEdit(self.range4_groupBox)
        self.range4_name_edit.setObjectName("range4_name_edit")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.range4_name_edit)
        self.label_12 = QtWidgets.QLabel(self.range4_groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.range4_lo_edit = XpdrCodeSpinBox(self.range4_groupBox)
        self.range4_lo_edit.setObjectName("range4_lo_edit")
        self.horizontalLayout_7.addWidget(self.range4_lo_edit)
        self.label_11 = QtWidgets.QLabel(self.range4_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.range4_hi_edit = XpdrCodeSpinBox(self.range4_groupBox)
        self.range4_hi_edit.setObjectName("range4_hi_edit")
        self.horizontalLayout_7.addWidget(self.range4_hi_edit)
        self.formLayout_10.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_20 = QtWidgets.QLabel(self.range4_groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.range4_colourPicker = ColourPicker(self.range4_groupBox)
        self.range4_colourPicker.setObjectName("range4_colourPicker")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.range4_colourPicker)
        self.gridLayout.addWidget(self.range4_groupBox, 2, 2, 1, 1)
        self.range1_groupBox = QtWidgets.QGroupBox(self.xpdrRanges_tab)
        self.range1_groupBox.setCheckable(True)
        self.range1_groupBox.setChecked(False)
        self.range1_groupBox.setObjectName("range1_groupBox")
        self.formLayout_7 = QtWidgets.QFormLayout(self.range1_groupBox)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label = QtWidgets.QLabel(self.range1_groupBox)
        self.label.setObjectName("label")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.range1_name_edit = QtWidgets.QLineEdit(self.range1_groupBox)
        self.range1_name_edit.setObjectName("range1_name_edit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.range1_name_edit)
        self.label_2 = QtWidgets.QLabel(self.range1_groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.range1_lo_edit = XpdrCodeSpinBox(self.range1_groupBox)
        self.range1_lo_edit.setObjectName("range1_lo_edit")
        self.horizontalLayout_3.addWidget(self.range1_lo_edit)
        self.label_3 = QtWidgets.QLabel(self.range1_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.range1_hi_edit = XpdrCodeSpinBox(self.range1_groupBox)
        self.range1_hi_edit.setObjectName("range1_hi_edit")
        self.horizontalLayout_3.addWidget(self.range1_hi_edit)
        self.formLayout_7.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_17 = QtWidgets.QLabel(self.range1_groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.range1_colourPicker = ColourPicker(self.range1_groupBox)
        self.range1_colourPicker.setObjectName("range1_colourPicker")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.range1_colourPicker)
        self.gridLayout.addWidget(self.range1_groupBox, 1, 0, 1, 1)
        self.range2_groupBox = QtWidgets.QGroupBox(self.xpdrRanges_tab)
        self.range2_groupBox.setCheckable(True)
        self.range2_groupBox.setChecked(False)
        self.range2_groupBox.setObjectName("range2_groupBox")
        self.formLayout_8 = QtWidgets.QFormLayout(self.range2_groupBox)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_4 = QtWidgets.QLabel(self.range2_groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.range2_name_edit = QtWidgets.QLineEdit(self.range2_groupBox)
        self.range2_name_edit.setObjectName("range2_name_edit")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.range2_name_edit)
        self.label_6 = QtWidgets.QLabel(self.range2_groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.range2_lo_edit = XpdrCodeSpinBox(self.range2_groupBox)
        self.range2_lo_edit.setObjectName("range2_lo_edit")
        self.horizontalLayout_5.addWidget(self.range2_lo_edit)
        self.label_5 = QtWidgets.QLabel(self.range2_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.range2_hi_edit = XpdrCodeSpinBox(self.range2_groupBox)
        self.range2_hi_edit.setObjectName("range2_hi_edit")
        self.horizontalLayout_5.addWidget(self.range2_hi_edit)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_18 = QtWidgets.QLabel(self.range2_groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.range2_colourPicker = ColourPicker(self.range2_groupBox)
        self.range2_colourPicker.setObjectName("range2_colourPicker")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.range2_colourPicker)
        self.gridLayout.addWidget(self.range2_groupBox, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.settings_tabs.addTab(self.xpdrRanges_tab, "")
        self.AD_tab = QtWidgets.QWidget()
        self.AD_tab.setObjectName("AD_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AD_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.soloSessions_AD_groupBox = QtWidgets.QGroupBox(self.AD_tab)
        self.soloSessions_AD_groupBox.setObjectName("soloSessions_AD_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.soloSessions_AD_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_33 = QtWidgets.QLabel(self.soloSessions_AD_groupBox)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 1, 2, 1, 1)
        self.spawnAPP_maxFL_edit = QtWidgets.QSpinBox(self.soloSessions_AD_groupBox)
        self.spawnAPP_maxFL_edit.setMinimum(50)
        self.spawnAPP_maxFL_edit.setMaximum(250)
        self.spawnAPP_maxFL_edit.setSingleStep(10)
        self.spawnAPP_maxFL_edit.setProperty("value", 170)
        self.spawnAPP_maxFL_edit.setObjectName("spawnAPP_maxFL_edit")
        self.gridLayout_3.addWidget(self.spawnAPP_maxFL_edit, 0, 3, 1, 1)
        self.TWRrangeCeiling_edit = QtWidgets.QSpinBox(self.soloSessions_AD_groupBox)
        self.TWRrangeCeiling_edit.setMinimum(20)
        self.TWRrangeCeiling_edit.setMaximum(100)
        self.TWRrangeCeiling_edit.setSingleStep(5)
        self.TWRrangeCeiling_edit.setObjectName("TWRrangeCeiling_edit")
        self.gridLayout_3.addWidget(self.TWRrangeCeiling_edit, 1, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.soloSessions_AD_groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.soloSessions_AD_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 2, 1, 1)
        self.spawnAPP_minFL_edit = QtWidgets.QSpinBox(self.soloSessions_AD_groupBox)
        self.spawnAPP_minFL_edit.setMinimum(50)
        self.spawnAPP_minFL_edit.setMaximum(250)
        self.spawnAPP_minFL_edit.setSingleStep(10)
        self.spawnAPP_minFL_edit.setProperty("value", 150)
        self.spawnAPP_minFL_edit.setObjectName("spawnAPP_minFL_edit")
        self.gridLayout_3.addWidget(self.spawnAPP_minFL_edit, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.soloSessions_AD_groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.TWRrangeDistance_edit = QtWidgets.QSpinBox(self.soloSessions_AD_groupBox)
        self.TWRrangeDistance_edit.setMinimum(5)
        self.TWRrangeDistance_edit.setMaximum(50)
        self.TWRrangeDistance_edit.setObjectName("TWRrangeDistance_edit")
        self.gridLayout_3.addWidget(self.TWRrangeDistance_edit, 1, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.soloSessions_AD_groupBox)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 2, 0, 1, 1)
        self.initialClimb_edit = QtWidgets.QLineEdit(self.soloSessions_AD_groupBox)
        self.initialClimb_edit.setObjectName("initialClimb_edit")
        self.gridLayout_3.addWidget(self.initialClimb_edit, 2, 1, 1, 3)
        self.verticalLayout_3.addWidget(self.soloSessions_AD_groupBox)
        self.atisTemplate_groupBox = QtWidgets.QGroupBox(self.AD_tab)
        self.atisTemplate_groupBox.setObjectName("atisTemplate_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.atisTemplate_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_34 = QtWidgets.QLabel(self.atisTemplate_groupBox)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_28 = QtWidgets.QLabel(self.atisTemplate_groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_28.setFont(font)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.atisTemplate_groupBox)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.atisCustomAppendix_edit = QtWidgets.QPlainTextEdit(self.atisTemplate_groupBox)
        self.atisCustomAppendix_edit.setTabChangesFocus(True)
        self.atisCustomAppendix_edit.setObjectName("atisCustomAppendix_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.atisCustomAppendix_edit)
        self.verticalLayout_3.addWidget(self.atisTemplate_groupBox)
        self.settings_tabs.addTab(self.AD_tab, "")
        self.CTR_tab = QtWidgets.QWidget()
        self.CTR_tab.setObjectName("CTR_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.CTR_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.soloSessions_CTR_groupBox = QtWidgets.QGroupBox(self.CTR_tab)
        self.soloSessions_CTR_groupBox.setObjectName("soloSessions_CTR_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.soloSessions_CTR_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_35 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 0, 0, 1, 1)
        self.spawnCTR_minFL_edit = QtWidgets.QSpinBox(self.soloSessions_CTR_groupBox)
        self.spawnCTR_minFL_edit.setMinimum(100)
        self.spawnCTR_minFL_edit.setMaximum(350)
        self.spawnCTR_minFL_edit.setSingleStep(10)
        self.spawnCTR_minFL_edit.setProperty("value", 270)
        self.spawnCTR_minFL_edit.setObjectName("spawnCTR_minFL_edit")
        self.gridLayout_2.addWidget(self.spawnCTR_minFL_edit, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 2, 1, 1)
        self.spawnCTR_maxFL_edit = QtWidgets.QSpinBox(self.soloSessions_CTR_groupBox)
        self.spawnCTR_maxFL_edit.setMinimum(100)
        self.spawnCTR_maxFL_edit.setMaximum(350)
        self.spawnCTR_maxFL_edit.setSingleStep(10)
        self.spawnCTR_maxFL_edit.setProperty("value", 330)
        self.spawnCTR_maxFL_edit.setObjectName("spawnCTR_maxFL_edit")
        self.gridLayout_2.addWidget(self.spawnCTR_maxFL_edit, 0, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 1, 0, 1, 1)
        self.CTRrangeDistance_edit = QtWidgets.QSpinBox(self.soloSessions_CTR_groupBox)
        self.CTRrangeDistance_edit.setMinimum(50)
        self.CTRrangeDistance_edit.setMaximum(500)
        self.CTRrangeDistance_edit.setProperty("value", 60)
        self.CTRrangeDistance_edit.setObjectName("CTRrangeDistance_edit")
        self.gridLayout_2.addWidget(self.CTRrangeDistance_edit, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 1, 2, 1, 2)
        self.label_39 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.soloSessions_CTR_groupBox)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 3, 0, 1, 1)
        self.routingPoints_edit = QtWidgets.QLineEdit(self.soloSessions_CTR_groupBox)
        self.routingPoints_edit.setObjectName("routingPoints_edit")
        self.gridLayout_2.addWidget(self.routingPoints_edit, 2, 1, 1, 3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.semiCircRule_radioButton_EW = QtWidgets.QRadioButton(self.soloSessions_CTR_groupBox)
        self.semiCircRule_radioButton_EW.setChecked(True)
        self.semiCircRule_radioButton_EW.setObjectName("semiCircRule_radioButton_EW")
        self.horizontalLayout_8.addWidget(self.semiCircRule_radioButton_EW)
        self.semiCircRule_radioButton_NS = QtWidgets.QRadioButton(self.soloSessions_CTR_groupBox)
        self.semiCircRule_radioButton_NS.setObjectName("semiCircRule_radioButton_NS")
        self.horizontalLayout_8.addWidget(self.semiCircRule_radioButton_NS)
        self.semiCircRule_radioButton_off = QtWidgets.QRadioButton(self.soloSessions_CTR_groupBox)
        self.semiCircRule_radioButton_off.setObjectName("semiCircRule_radioButton_off")
        self.horizontalLayout_8.addWidget(self.semiCircRule_radioButton_off)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 1, 1, 3)
        self.label_39.raise_()
        self.label_35.raise_()
        self.spawnCTR_maxFL_edit.raise_()
        self.label_37.raise_()
        self.spawnCTR_minFL_edit.raise_()
        self.label_36.raise_()
        self.CTRrangeDistance_edit.raise_()
        self.label_42.raise_()
        self.routingPoints_edit.raise_()
        self.label_41.raise_()
        self.verticalLayout_5.addWidget(self.soloSessions_CTR_groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.settings_tabs.addTab(self.CTR_tab, "")
        self.verticalLayout.addWidget(self.settings_tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(localSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_26.setBuddy(self.radarHorizontalRange_edit)
        self.label_25.setBuddy(self.radarFloor_edit)
        self.label_24.setBuddy(self.capability_noSSR_radioButton)
        self.label_27.setBuddy(self.radarUpdateInterval_edit)
        self.label_14.setBuddy(self.stripAutoPrint_DEP_tickBox)
        self.label_40.setBuddy(self.stripAutoPrint_leadTime_edit)
        self.label_21.setBuddy(self.horizontalSeparation_edit)
        self.label_22.setBuddy(self.verticalSeparation_edit)
        self.label_23.setBuddy(self.conflictWarningFloorFL_edit)
        self.label_16.setBuddy(self.transitionAltitude_edit)
        self.label_13.setBuddy(self.uncontrolledVFRcode_edit)
        self.label_15.setBuddy(self.radioName_edit)
        self.label_7.setBuddy(self.range3_name_edit)
        self.label_9.setBuddy(self.range3_lo_edit)
        self.label_8.setBuddy(self.range3_hi_edit)
        self.label_10.setBuddy(self.range4_name_edit)
        self.label_12.setBuddy(self.range4_lo_edit)
        self.label_11.setBuddy(self.range4_hi_edit)
        self.label.setBuddy(self.range1_name_edit)
        self.label_2.setBuddy(self.range1_lo_edit)
        self.label_3.setBuddy(self.range1_hi_edit)
        self.label_4.setBuddy(self.range2_name_edit)
        self.label_6.setBuddy(self.range2_lo_edit)
        self.label_5.setBuddy(self.range2_hi_edit)
        self.label_33.setBuddy(self.TWRrangeCeiling_edit)
        self.label_32.setBuddy(self.TWRrangeDistance_edit)
        self.label_31.setBuddy(self.spawnAPP_maxFL_edit)
        self.label_30.setBuddy(self.spawnAPP_minFL_edit)
        self.label_43.setBuddy(self.initialClimb_edit)
        self.label_29.setBuddy(self.atisCustomAppendix_edit)
        self.label_35.setBuddy(self.spawnCTR_minFL_edit)
        self.label_36.setBuddy(self.spawnCTR_maxFL_edit)
        self.label_37.setBuddy(self.CTRrangeDistance_edit)
        self.label_42.setBuddy(self.CTRrangeDistance_edit)
        self.label_39.setBuddy(self.routingPoints_edit)
        self.label_41.setBuddy(self.semiCircRule_radioButton_EW)

        self.retranslateUi(localSettingsDialog)
        self.settings_tabs.setCurrentIndex(0)
        self.buttonBox.rejected.connect(localSettingsDialog.reject)
        self.range1_groupBox.toggled['bool'].connect(self.range1_name_edit.setFocus)
        self.range4_groupBox.toggled['bool'].connect(self.range4_name_edit.setFocus)
        self.range3_groupBox.toggled['bool'].connect(self.range3_name_edit.setFocus)
        self.range2_groupBox.toggled['bool'].connect(self.range2_name_edit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(localSettingsDialog)
        localSettingsDialog.setTabOrder(self.settings_tabs, self.capability_noSSR_radioButton)
        localSettingsDialog.setTabOrder(self.capability_noSSR_radioButton, self.capability_modeA_radioButton)
        localSettingsDialog.setTabOrder(self.capability_modeA_radioButton, self.capability_modeC_radioButton)
        localSettingsDialog.setTabOrder(self.capability_modeC_radioButton, self.capability_modeS_radioButton)
        localSettingsDialog.setTabOrder(self.capability_modeS_radioButton, self.radarHorizontalRange_edit)
        localSettingsDialog.setTabOrder(self.radarHorizontalRange_edit, self.radarFloor_edit)
        localSettingsDialog.setTabOrder(self.radarFloor_edit, self.radarUpdateInterval_edit)
        localSettingsDialog.setTabOrder(self.radarUpdateInterval_edit, self.radioDirectionFinding_tickBox)
        localSettingsDialog.setTabOrder(self.radioDirectionFinding_tickBox, self.cpdlc_tickBox)
        localSettingsDialog.setTabOrder(self.cpdlc_tickBox, self.stripAutoPrint_DEP_tickBox)
        localSettingsDialog.setTabOrder(self.stripAutoPrint_DEP_tickBox, self.stripAutoPrint_ARR_tickBox)
        localSettingsDialog.setTabOrder(self.stripAutoPrint_ARR_tickBox, self.stripAutoPrint_ifrOnly_tickBox)
        localSettingsDialog.setTabOrder(self.stripAutoPrint_ifrOnly_tickBox, self.stripAutoPrint_leadTime_edit)
        localSettingsDialog.setTabOrder(self.stripAutoPrint_leadTime_edit, self.horizontalSeparation_edit)
        localSettingsDialog.setTabOrder(self.horizontalSeparation_edit, self.verticalSeparation_edit)
        localSettingsDialog.setTabOrder(self.verticalSeparation_edit, self.conflictWarningFloorFL_edit)
        localSettingsDialog.setTabOrder(self.conflictWarningFloorFL_edit, self.transitionAltitude_edit)
        localSettingsDialog.setTabOrder(self.transitionAltitude_edit, self.uncontrolledVFRcode_edit)
        localSettingsDialog.setTabOrder(self.uncontrolledVFRcode_edit, self.radioName_edit)
        localSettingsDialog.setTabOrder(self.radioName_edit, self.range1_groupBox)
        localSettingsDialog.setTabOrder(self.range1_groupBox, self.range1_name_edit)
        localSettingsDialog.setTabOrder(self.range1_name_edit, self.range1_lo_edit)
        localSettingsDialog.setTabOrder(self.range1_lo_edit, self.range1_hi_edit)
        localSettingsDialog.setTabOrder(self.range1_hi_edit, self.range2_groupBox)
        localSettingsDialog.setTabOrder(self.range2_groupBox, self.range2_name_edit)
        localSettingsDialog.setTabOrder(self.range2_name_edit, self.range2_lo_edit)
        localSettingsDialog.setTabOrder(self.range2_lo_edit, self.range2_hi_edit)
        localSettingsDialog.setTabOrder(self.range2_hi_edit, self.range3_groupBox)
        localSettingsDialog.setTabOrder(self.range3_groupBox, self.range3_name_edit)
        localSettingsDialog.setTabOrder(self.range3_name_edit, self.range3_lo_edit)
        localSettingsDialog.setTabOrder(self.range3_lo_edit, self.range3_hi_edit)
        localSettingsDialog.setTabOrder(self.range3_hi_edit, self.range4_groupBox)
        localSettingsDialog.setTabOrder(self.range4_groupBox, self.range4_name_edit)
        localSettingsDialog.setTabOrder(self.range4_name_edit, self.range4_lo_edit)
        localSettingsDialog.setTabOrder(self.range4_lo_edit, self.range4_hi_edit)
        localSettingsDialog.setTabOrder(self.range4_hi_edit, self.spawnAPP_minFL_edit)
        localSettingsDialog.setTabOrder(self.spawnAPP_minFL_edit, self.spawnAPP_maxFL_edit)
        localSettingsDialog.setTabOrder(self.spawnAPP_maxFL_edit, self.TWRrangeDistance_edit)
        localSettingsDialog.setTabOrder(self.TWRrangeDistance_edit, self.TWRrangeCeiling_edit)
        localSettingsDialog.setTabOrder(self.TWRrangeCeiling_edit, self.initialClimb_edit)
        localSettingsDialog.setTabOrder(self.initialClimb_edit, self.atisCustomAppendix_edit)
        localSettingsDialog.setTabOrder(self.atisCustomAppendix_edit, self.spawnCTR_minFL_edit)
        localSettingsDialog.setTabOrder(self.spawnCTR_minFL_edit, self.spawnCTR_maxFL_edit)
        localSettingsDialog.setTabOrder(self.spawnCTR_maxFL_edit, self.CTRrangeDistance_edit)
        localSettingsDialog.setTabOrder(self.CTRrangeDistance_edit, self.routingPoints_edit)
        localSettingsDialog.setTabOrder(self.routingPoints_edit, self.semiCircRule_radioButton_EW)
        localSettingsDialog.setTabOrder(self.semiCircRule_radioButton_EW, self.semiCircRule_radioButton_NS)
        localSettingsDialog.setTabOrder(self.semiCircRule_radioButton_NS, self.semiCircRule_radioButton_off)
        localSettingsDialog.setTabOrder(self.semiCircRule_radioButton_off, self.buttonBox)

    def retranslateUi(self, localSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        localSettingsDialog.setWindowTitle(_translate("localSettingsDialog", "Location settings"))
        self.groupBox_12.setTitle(_translate("localSettingsDialog", "Radar"))
        self.label_26.setText(_translate("localSettingsDialog", "Horizontal range:"))
        self.radarHorizontalRange_edit.setSuffix(_translate("localSettingsDialog", " NM"))
        self.label_25.setText(_translate("localSettingsDialog", "Floor altitude:"))
        self.radarFloor_edit.setToolTip(_translate("localSettingsDialog", "Minimum altitude for transponder signal pick-up (geometric measurement, not a pressure-alt.)"))
        self.radarFloor_edit.setSpecialValueText(_translate("localSettingsDialog", "SFC"))
        self.radarFloor_edit.setSuffix(_translate("localSettingsDialog", " ft AMSL"))
        self.label_24.setText(_translate("localSettingsDialog", "SSR mode capability:"))
        self.capability_noSSR_radioButton.setText(_translate("localSettingsDialog", "None"))
        self.capability_modeA_radioButton.setText(_translate("localSettingsDialog", "A"))
        self.capability_modeC_radioButton.setText(_translate("localSettingsDialog", "C"))
        self.capability_modeS_radioButton.setText(_translate("localSettingsDialog", "S"))
        self.label_27.setText(_translate("localSettingsDialog", "Sweep interval:"))
        self.radarUpdateInterval_edit.setToolTip(_translate("localSettingsDialog", "Radar rotation (scan) period"))
        self.radarUpdateInterval_edit.setSuffix(_translate("localSettingsDialog", " s"))
        self.groupBox.setTitle(_translate("localSettingsDialog", "Communications"))
        self.radioDirectionFinding_tickBox.setText(_translate("localSettingsDialog", "Radio direction finding (RDF)"))
        self.cpdlc_tickBox.setText(_translate("localSettingsDialog", "Controller–pilot data link (CPDLC)"))
        self.stripPrinter_groupBox.setTitle(_translate("localSettingsDialog", "Strip printer"))
        self.label_14.setText(_translate("localSettingsDialog", "Auto-print strips:"))
        self.stripAutoPrint_DEP_tickBox.setToolTip(_translate("localSettingsDialog", "if FPL not closed"))
        self.stripAutoPrint_DEP_tickBox.setText(_translate("localSettingsDialog", "for filed departures"))
        self.stripAutoPrint_ARR_tickBox.setToolTip(_translate("localSettingsDialog", "if FPL open"))
        self.stripAutoPrint_ARR_tickBox.setText(_translate("localSettingsDialog", "for filed arrivals"))
        self.stripAutoPrint_ifrOnly_tickBox.setText(_translate("localSettingsDialog", "IFR only"))
        self.stripAutoPrint_leadTime_edit.setSuffix(_translate("localSettingsDialog", " min"))
        self.label_40.setText(_translate("localSettingsDialog", "Lead time:"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.radar_tab), _translate("localSettingsDialog", "Equipment"))
        self.groupBox_11.setTitle(_translate("localSettingsDialog", "Aircraft separation"))
        self.label_21.setText(_translate("localSettingsDialog", "Horizontal:"))
        self.horizontalSeparation_edit.setSuffix(_translate("localSettingsDialog", " NM"))
        self.label_22.setText(_translate("localSettingsDialog", "Vertical:"))
        self.verticalSeparation_edit.setSuffix(_translate("localSettingsDialog", " ft"))
        self.label_23.setText(_translate("localSettingsDialog", "At and above:"))
        self.conflictWarningFloorFL_edit.setToolTip(_translate("localSettingsDialog", "Path/route conflicts will not be reported if involving aircraft under this level"))
        self.conflictWarningFloorFL_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.groupBox_2.setTitle(_translate("localSettingsDialog", "Misc."))
        self.label_16.setText(_translate("localSettingsDialog", "Transition altitude:"))
        self.transitionAltitude_edit.setSuffix(_translate("localSettingsDialog", " ft"))
        self.label_13.setText(_translate("localSettingsDialog", "Default VFR code:"))
        self.label_15.setText(_translate("localSettingsDialog", "Radio callsign:"))
        self.radioName_edit.setToolTip(_translate("localSettingsDialog", "Defines text alias $me, and called by AI pilots on initial contact (solo sessions)."))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.rules_tab), _translate("localSettingsDialog", "Rules"))
        self.range3_groupBox.setTitle(_translate("localSettingsDialog", "Assignment range"))
        self.label_7.setText(_translate("localSettingsDialog", "Name:"))
        self.label_9.setText(_translate("localSettingsDialog", "Code range:"))
        self.label_8.setText(_translate("localSettingsDialog", "to"))
        self.label_19.setText(_translate("localSettingsDialog", "Radar colour:"))
        self.range4_groupBox.setTitle(_translate("localSettingsDialog", "Assignment range"))
        self.label_10.setText(_translate("localSettingsDialog", "Name:"))
        self.label_12.setText(_translate("localSettingsDialog", "Code range:"))
        self.label_11.setText(_translate("localSettingsDialog", "to"))
        self.label_20.setText(_translate("localSettingsDialog", "Radar colour:"))
        self.range1_groupBox.setTitle(_translate("localSettingsDialog", "Assignment range"))
        self.label.setText(_translate("localSettingsDialog", "Name:"))
        self.label_2.setText(_translate("localSettingsDialog", "Code range:"))
        self.label_3.setText(_translate("localSettingsDialog", "to"))
        self.label_17.setText(_translate("localSettingsDialog", "Radar colour:"))
        self.range2_groupBox.setTitle(_translate("localSettingsDialog", "Assignment range"))
        self.label_4.setText(_translate("localSettingsDialog", "Name:"))
        self.label_6.setText(_translate("localSettingsDialog", "Code range:"))
        self.label_5.setText(_translate("localSettingsDialog", "to"))
        self.label_18.setText(_translate("localSettingsDialog", "Radar colour:"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.xpdrRanges_tab), _translate("localSettingsDialog", "Transponder ranges"))
        self.soloSessions_AD_groupBox.setTitle(_translate("localSettingsDialog", "Solo sessions"))
        self.label_33.setText(_translate("localSettingsDialog", "/"))
        self.spawnAPP_maxFL_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.TWRrangeCeiling_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.label_32.setText(_translate("localSettingsDialog", "TWR range:"))
        self.label_31.setText(_translate("localSettingsDialog", "and"))
        self.spawnAPP_minFL_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.label_30.setText(_translate("localSettingsDialog", "APP receives aircraft between:"))
        self.TWRrangeDistance_edit.setSuffix(_translate("localSettingsDialog", " NM"))
        self.label_43.setText(_translate("localSettingsDialog", "Iinital climb (unless instructed otherwise):"))
        self.initialClimb_edit.setToolTip(_translate("localSettingsDialog", "FL or ft"))
        self.initialClimb_edit.setPlaceholderText(_translate("localSettingsDialog", "(required)"))
        self.atisTemplate_groupBox.setTitle(_translate("localSettingsDialog", "ATIS template"))
        self.label_34.setText(_translate("localSettingsDialog", "Standard contents:"))
        self.label_28.setText(_translate("localSettingsDialog", "Location callsign, information letter, time of recording, runway use, weather"))
        self.label_29.setText(_translate("localSettingsDialog", "Custom appendix:"))
        self.atisCustomAppendix_edit.setToolTip(_translate("localSettingsDialog", "Text aliases allowed"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.AD_tab), _translate("localSettingsDialog", "AD settings"))
        self.soloSessions_CTR_groupBox.setTitle(_translate("localSettingsDialog", "Solo sessions"))
        self.label_35.setText(_translate("localSettingsDialog", "CTR receives aircraft between:"))
        self.spawnCTR_minFL_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.label_36.setText(_translate("localSettingsDialog", "and"))
        self.spawnCTR_maxFL_edit.setPrefix(_translate("localSettingsDialog", "FL"))
        self.label_37.setText(_translate("localSettingsDialog", "Hand over aircraft past:"))
        self.CTRrangeDistance_edit.setSuffix(_translate("localSettingsDialog", " NM"))
        self.label_42.setText(_translate("localSettingsDialog", "from radar centre"))
        self.label_39.setText(_translate("localSettingsDialog", "Turning points:"))
        self.label_41.setText(_translate("localSettingsDialog", "Semi-circular rule:"))
        self.routingPoints_edit.setToolTip(_translate("localSettingsDialog", "Separate with whitespace"))
        self.routingPoints_edit.setPlaceholderText(_translate("localSettingsDialog", "None"))
        self.semiCircRule_radioButton_EW.setText(_translate("localSettingsDialog", "E/W"))
        self.semiCircRule_radioButton_NS.setText(_translate("localSettingsDialog", "N/S"))
        self.semiCircRule_radioButton_off.setText(_translate("localSettingsDialog", "Off"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.CTR_tab), _translate("localSettingsDialog", "CTR settings"))

from gui.widgets.basicWidgets import XpdrCodeSpinBox
from gui.widgets.miscWidgets import ColourPicker
