from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_looseStripPane(object):
    def setupUi(self, looseStripPane):
        looseStripPane.setObjectName("looseStripPane")
        looseStripPane.resize(578, 363)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(looseStripPane.sizePolicy().hasHeightForWidth())
        looseStripPane.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(looseStripPane)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stripView = QtWidgets.QGraphicsView(looseStripPane)
        self.stripView.setInteractive(True)
        self.stripView.setObjectName("stripView")
        self.verticalLayout.addWidget(self.stripView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.background_menuButton = QtWidgets.QToolButton(looseStripPane)
        self.background_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.background_menuButton.setObjectName("background_menuButton")
        self.horizontalLayout_3.addWidget(self.background_menuButton)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.compactStrips_tickBox = QtWidgets.QCheckBox(looseStripPane)
        self.compactStrips_tickBox.setObjectName("compactStrips_tickBox")
        self.horizontalLayout_3.addWidget(self.compactStrips_tickBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.deleteStrip_button = QtWidgets.QToolButton(looseStripPane)
        self.deleteStrip_button.setObjectName("deleteStrip_button")
        self.horizontalLayout_3.addWidget(self.deleteStrip_button)
        self.frame = QtWidgets.QFrame(looseStripPane)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shelf_button = ShelfButtonWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy)
        self.shelf_button.setMinimumSize(QtCore.QSize(50, 0))
        self.shelf_button.setObjectName("shelf_button")
        self.horizontalLayout.addWidget(self.shelf_button)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(looseStripPane)
        QtCore.QMetaObject.connectSlotsByName(looseStripPane)

    def retranslateUi(self, looseStripPane):
        _translate = QtCore.QCoreApplication.translate
        looseStripPane.setWindowTitle(_translate("looseStripPane", "Loose strip bay"))
        self.background_menuButton.setText(_translate("looseStripPane", "Bg"))
        self.compactStrips_tickBox.setText(_translate("looseStripPane", "Compact strips"))
        self.deleteStrip_button.setToolTip(_translate("looseStripPane", "Delete strip"))
        self.deleteStrip_button.setText(_translate("looseStripPane", "- strip"))

from gui.widgets.basicWidgets import ShelfButtonWidget
