
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_routeEditWidget(object):
    def setupUi(self, routeEditWidget):
        routeEditWidget.setObjectName("routeEditWidget")
        routeEditWidget.resize(321, 148)
        self.horizontalLayout = QtWidgets.QHBoxLayout(routeEditWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.route_edit = QtWidgets.QPlainTextEdit(routeEditWidget)
        self.route_edit.setTabChangesFocus(True)
        self.route_edit.setObjectName("route_edit")
        self.horizontalLayout.addWidget(self.route_edit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.recall_button = QtWidgets.QToolButton(routeEditWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recall_button.setFont(font)
        self.recall_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.recall_button.setAutoRaise(True)
        self.recall_button.setObjectName("recall_button")
        self.gridLayout.addWidget(self.recall_button, 0, 1, 1, 1)
        self.suggest_button = QtWidgets.QToolButton(routeEditWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.suggest_button.setFont(font)
        self.suggest_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.suggest_button.setAutoRaise(True)
        self.suggest_button.setObjectName("suggest_button")
        self.gridLayout.addWidget(self.suggest_button, 0, 0, 1, 1)
        self.view_button = QtWidgets.QToolButton(routeEditWidget)
        self.view_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.view_button.setObjectName("view_button")
        self.gridLayout.addWidget(self.view_button, 1, 0, 1, 1)
        self.saveAsPreset_button = QtWidgets.QToolButton(routeEditWidget)
        self.saveAsPreset_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveAsPreset_button.setAutoRaise(True)
        self.saveAsPreset_button.setObjectName("saveAsPreset_button")
        self.gridLayout.addWidget(self.saveAsPreset_button, 1, 1, 1, 1)
        self.clear_button = QtWidgets.QToolButton(routeEditWidget)
        self.clear_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clear_button.setAutoRaise(True)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(routeEditWidget)
        QtCore.QMetaObject.connectSlotsByName(routeEditWidget)

    def retranslateUi(self, routeEditWidget):
        _translate = QtCore.QCoreApplication.translate
        self.recall_button.setToolTip(_translate("routeEditWidget", "Recall a saved preset"))
        self.recall_button.setText(_translate("routeEditWidget", "R"))
        self.suggest_button.setToolTip(_translate("routeEditWidget", "Suggest a route"))
        self.suggest_button.setText(_translate("routeEditWidget", "S"))
        self.view_button.setToolTip(_translate("routeEditWidget", "View parsed route details"))
        self.view_button.setText(_translate("routeEditWidget", "V"))
        self.saveAsPreset_button.setToolTip(_translate("routeEditWidget", "Save current entry as route preset"))
        self.saveAsPreset_button.setText(_translate("routeEditWidget", "S"))
        self.clear_button.setToolTip(_translate("routeEditWidget", "Clear route"))
        self.clear_button.setText(_translate("routeEditWidget", "X"))

