
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_routeDialog(object):
    def setupUi(self, routeDialog):
        routeDialog.setObjectName("routeDialog")
        routeDialog.resize(517, 615)
        self.verticalLayout = QtWidgets.QVBoxLayout(routeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(routeDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.arrAD_info = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrAD_info.sizePolicy().hasHeightForWidth())
        self.arrAD_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.arrAD_info.setFont(font)
        self.arrAD_info.setObjectName("arrAD_info")
        self.gridLayout.addWidget(self.arrAD_info, 1, 2, 1, 1)
        self.arrICAO_info = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.arrICAO_info.setFont(font)
        self.arrICAO_info.setObjectName("arrICAO_info")
        self.gridLayout.addWidget(self.arrICAO_info, 1, 1, 1, 1)
        self.depAD_info = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depAD_info.sizePolicy().hasHeightForWidth())
        self.depAD_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.depAD_info.setFont(font)
        self.depAD_info.setObjectName("depAD_info")
        self.gridLayout.addWidget(self.depAD_info, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.depICAO_info = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.depICAO_info.setFont(font)
        self.depICAO_info.setObjectName("depICAO_info")
        self.gridLayout.addWidget(self.depICAO_info, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.route_table = QtWidgets.QTableView(routeDialog)
        self.route_table.setAlternatingRowColors(True)
        self.route_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.route_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.route_table.setObjectName("route_table")
        self.verticalLayout.addWidget(self.route_table)
        self.frame = QtWidgets.QFrame(routeDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.totalRouteDistance_info = QtWidgets.QLabel(self.frame)
        self.totalRouteDistance_info.setObjectName("totalRouteDistance_info")
        self.gridLayout_3.addWidget(self.totalRouteDistance_info, 0, 1, 1, 1)
        self.EETfromSpeed_radioButton = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EETfromSpeed_radioButton.sizePolicy().hasHeightForWidth())
        self.EETfromSpeed_radioButton.setSizePolicy(sizePolicy)
        self.EETfromSpeed_radioButton.setChecked(True)
        self.EETfromSpeed_radioButton.setObjectName("EETfromSpeed_radioButton")
        self.gridLayout_3.addWidget(self.EETfromSpeed_radioButton, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 2, 2, 1)
        self.EET_info = QtWidgets.QLabel(self.frame)
        self.EET_info.setObjectName("EET_info")
        self.gridLayout_3.addWidget(self.EET_info, 1, 1, 1, 1)
        self.speed_edit = QtWidgets.QSpinBox(self.frame)
        self.speed_edit.setMinimum(50)
        self.speed_edit.setMaximum(999)
        self.speed_edit.setSingleStep(10)
        self.speed_edit.setProperty("value", 100)
        self.speed_edit.setObjectName("speed_edit")
        self.gridLayout_3.addWidget(self.speed_edit, 0, 4, 1, 1)
        self.EETfromACFT_radioButton = QtWidgets.QRadioButton(self.frame)
        self.EETfromACFT_radioButton.setObjectName("EETfromACFT_radioButton")
        self.gridLayout_3.addWidget(self.EETfromACFT_radioButton, 1, 3, 1, 1)
        self.acftType_select = AircraftTypeCombo(self.frame)
        self.acftType_select.setEnabled(False)
        self.acftType_select.setEditable(True)
        self.acftType_select.setObjectName("acftType_select")
        self.gridLayout_3.addWidget(self.acftType_select, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.route_view = RouteView(routeDialog)
        self.route_view.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.route_view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.route_view.setObjectName("route_view")
        self.verticalLayout.addWidget(self.route_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OK_button = QtWidgets.QPushButton(routeDialog)
        self.OK_button.setObjectName("OK_button")
        self.horizontalLayout.addWidget(self.OK_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(routeDialog)
        self.EETfromSpeed_radioButton.toggled['bool'].connect(self.speed_edit.setEnabled)
        self.EETfromACFT_radioButton.toggled['bool'].connect(self.acftType_select.setEnabled)
        self.EETfromSpeed_radioButton.toggled['bool'].connect(self.speed_edit.setFocus)
        self.EETfromACFT_radioButton.toggled['bool'].connect(self.acftType_select.setFocus)
        QtCore.QMetaObject.connectSlotsByName(routeDialog)
        routeDialog.setTabOrder(self.route_table, self.EETfromSpeed_radioButton)
        routeDialog.setTabOrder(self.EETfromSpeed_radioButton, self.speed_edit)
        routeDialog.setTabOrder(self.speed_edit, self.EETfromACFT_radioButton)
        routeDialog.setTabOrder(self.EETfromACFT_radioButton, self.acftType_select)
        routeDialog.setTabOrder(self.acftType_select, self.OK_button)

    def retranslateUi(self, routeDialog):
        _translate = QtCore.QCoreApplication.translate
        routeDialog.setWindowTitle(_translate("routeDialog", "Route view"))
        self.arrAD_info.setText(_translate("routeDialog", "##"))
        self.arrICAO_info.setText(_translate("routeDialog", "##"))
        self.depAD_info.setText(_translate("routeDialog", "##"))
        self.label_2.setText(_translate("routeDialog", "Arrival (red on map):"))
        self.depICAO_info.setText(_translate("routeDialog", "##"))
        self.label.setText(_translate("routeDialog", "Departure (yellow on map):"))
        self.totalRouteDistance_info.setText(_translate("routeDialog", "##"))
        self.EETfromSpeed_radioButton.setText(_translate("routeDialog", "EET from speed:"))
        self.label_3.setText(_translate("routeDialog", "Total route distance:"))
        self.label_4.setText(_translate("routeDialog", "Est. en-route time:"))
        self.EET_info.setText(_translate("routeDialog", "##"))
        self.speed_edit.setSuffix(_translate("routeDialog", " kt"))
        self.EETfromACFT_radioButton.setText(_translate("routeDialog", "EET from ACFT type:"))
        self.OK_button.setText(_translate("routeDialog", "OK"))

from gui.widgets.basicWidgets import AircraftTypeCombo
from gui.widgets.routeWidgets import RouteView
