
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_soloSessionSettingsDialog(object):
    def setupUi(self, soloSessionSettingsDialog):
        soloSessionSettingsDialog.setObjectName("soloSessionSettingsDialog")
        soloSessionSettingsDialog.resize(369, 503)
        self.verticalLayout = QtWidgets.QVBoxLayout(soloSessionSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(soloSessionSettingsDialog)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cpdlcConnections_widget = QtWidgets.QWidget(self.groupBox_10)
        self.cpdlcConnections_widget.setObjectName("cpdlcConnections_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cpdlcConnections_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.cpdlcConnections_widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cpdlcConnectionBalance_edit = QtWidgets.QSlider(self.cpdlcConnections_widget)
        self.cpdlcConnectionBalance_edit.setMaximum(100)
        self.cpdlcConnectionBalance_edit.setOrientation(QtCore.Qt.Horizontal)
        self.cpdlcConnectionBalance_edit.setObjectName("cpdlcConnectionBalance_edit")
        self.horizontalLayout_3.addWidget(self.cpdlcConnectionBalance_edit)
        self.label_3 = QtWidgets.QLabel(self.cpdlcConnections_widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout_4.addWidget(self.cpdlcConnections_widget, 3, 1, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.maxSpawnDelay_minutes_edit = QtWidgets.QSpinBox(self.groupBox_10)
        self.maxSpawnDelay_minutes_edit.setMinimum(2)
        self.maxSpawnDelay_minutes_edit.setMaximum(15)
        self.maxSpawnDelay_minutes_edit.setObjectName("maxSpawnDelay_minutes_edit")
        self.gridLayout_4.addWidget(self.maxSpawnDelay_minutes_edit, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.minSpawnDelay_seconds_edit = QtWidgets.QSpinBox(self.groupBox_10)
        self.minSpawnDelay_seconds_edit.setMinimum(1)
        self.minSpawnDelay_seconds_edit.setMaximum(119)
        self.minSpawnDelay_seconds_edit.setObjectName("minSpawnDelay_seconds_edit")
        self.gridLayout_4.addWidget(self.minSpawnDelay_seconds_edit, 1, 1, 1, 1)
        self.maxAircraftCount_edit = QtWidgets.QSpinBox(self.groupBox_10)
        self.maxAircraftCount_edit.setMinimum(1)
        self.maxAircraftCount_edit.setObjectName("maxAircraftCount_edit")
        self.gridLayout_4.addWidget(self.maxAircraftCount_edit, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 2, 1, 1)
        self.cpdlcConnections_label = QtWidgets.QLabel(self.groupBox_10)
        self.cpdlcConnections_label.setObjectName("cpdlcConnections_label")
        self.gridLayout_4.addWidget(self.cpdlcConnections_label, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_10)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.distractorCount_edit = QtWidgets.QSpinBox(self.groupBox_10)
        self.distractorCount_edit.setObjectName("distractorCount_edit")
        self.gridLayout_4.addWidget(self.distractorCount_edit, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.airportMode_groupBox = QtWidgets.QGroupBox(soloSessionSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airportMode_groupBox.sizePolicy().hasHeightForWidth())
        self.airportMode_groupBox.setSizePolicy(sizePolicy)
        self.airportMode_groupBox.setObjectName("airportMode_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.airportMode_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.airportMode_groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.ARRvsDEP_edit = QtWidgets.QSlider(self.airportMode_groupBox)
        self.ARRvsDEP_edit.setMaximum(100)
        self.ARRvsDEP_edit.setOrientation(QtCore.Qt.Horizontal)
        self.ARRvsDEP_edit.setObjectName("ARRvsDEP_edit")
        self.gridLayout_3.addWidget(self.ARRvsDEP_edit, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.airportMode_groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.airportMode_groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.ILSvsVisual_edit = QtWidgets.QSlider(self.airportMode_groupBox)
        self.ILSvsVisual_edit.setMaximum(100)
        self.ILSvsVisual_edit.setOrientation(QtCore.Qt.Horizontal)
        self.ILSvsVisual_edit.setObjectName("ILSvsVisual_edit")
        self.gridLayout_3.addWidget(self.ILSvsVisual_edit, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.airportMode_groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.airportMode_groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(soloSessionSettingsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.soloWeatherChangeInterval_edit = QtWidgets.QSpinBox(self.groupBox_2)
        self.soloWeatherChangeInterval_edit.setMaximum(120)
        self.soloWeatherChangeInterval_edit.setSingleStep(5)
        self.soloWeatherChangeInterval_edit.setObjectName("soloWeatherChangeInterval_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.soloWeatherChangeInterval_edit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(soloSessionSettingsDialog)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.voiceInstr_off_radioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.voiceInstr_off_radioButton.setObjectName("voiceInstr_off_radioButton")
        self.verticalLayout_9.addWidget(self.voiceInstr_off_radioButton)
        self.voiceInstr_on_radioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.voiceInstr_on_radioButton.setObjectName("voiceInstr_on_radioButton")
        self.verticalLayout_9.addWidget(self.voiceInstr_on_radioButton)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.line = QtWidgets.QFrame(soloSessionSettingsDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.groupBox_11 = QtWidgets.QGroupBox(soloSessionSettingsDialog)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.readBack_off_radioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.readBack_off_radioButton.setObjectName("readBack_off_radioButton")
        self.verticalLayout_10.addWidget(self.readBack_off_radioButton)
        self.readBack_wilcoBeep_radioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.readBack_wilcoBeep_radioButton.setObjectName("readBack_wilcoBeep_radioButton")
        self.verticalLayout_10.addWidget(self.readBack_wilcoBeep_radioButton)
        self.readBack_voice_radioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.readBack_voice_radioButton.setObjectName("readBack_voice_radioButton")
        self.verticalLayout_10.addWidget(self.readBack_voice_radioButton)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(soloSessionSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_4.setBuddy(self.cpdlcConnectionBalance_edit)
        self.label_3.setBuddy(self.cpdlcConnectionBalance_edit)
        self.label_22.setBuddy(self.maxAircraftCount_edit)
        self.label_19.setBuddy(self.minSpawnDelay_seconds_edit)
        self.label_21.setBuddy(self.maxSpawnDelay_minutes_edit)
        self.cpdlcConnections_label.setBuddy(self.cpdlcConnectionBalance_edit)
        self.label.setBuddy(self.distractorCount_edit)
        self.label_11.setBuddy(self.ARRvsDEP_edit)
        self.label_18.setBuddy(self.ARRvsDEP_edit)
        self.label_16.setBuddy(self.ILSvsVisual_edit)
        self.label_17.setBuddy(self.ILSvsVisual_edit)
        self.label_20.setBuddy(self.soloWeatherChangeInterval_edit)

        self.retranslateUi(soloSessionSettingsDialog)
        self.buttonBox.rejected.connect(soloSessionSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(soloSessionSettingsDialog)
        soloSessionSettingsDialog.setTabOrder(self.maxAircraftCount_edit, self.minSpawnDelay_seconds_edit)
        soloSessionSettingsDialog.setTabOrder(self.minSpawnDelay_seconds_edit, self.maxSpawnDelay_minutes_edit)
        soloSessionSettingsDialog.setTabOrder(self.maxSpawnDelay_minutes_edit, self.cpdlcConnectionBalance_edit)
        soloSessionSettingsDialog.setTabOrder(self.cpdlcConnectionBalance_edit, self.distractorCount_edit)
        soloSessionSettingsDialog.setTabOrder(self.distractorCount_edit, self.ARRvsDEP_edit)
        soloSessionSettingsDialog.setTabOrder(self.ARRvsDEP_edit, self.ILSvsVisual_edit)
        soloSessionSettingsDialog.setTabOrder(self.ILSvsVisual_edit, self.soloWeatherChangeInterval_edit)
        soloSessionSettingsDialog.setTabOrder(self.soloWeatherChangeInterval_edit, self.voiceInstr_off_radioButton)
        soloSessionSettingsDialog.setTabOrder(self.voiceInstr_off_radioButton, self.voiceInstr_on_radioButton)
        soloSessionSettingsDialog.setTabOrder(self.voiceInstr_on_radioButton, self.readBack_off_radioButton)
        soloSessionSettingsDialog.setTabOrder(self.readBack_off_radioButton, self.readBack_wilcoBeep_radioButton)
        soloSessionSettingsDialog.setTabOrder(self.readBack_wilcoBeep_radioButton, self.readBack_voice_radioButton)
        soloSessionSettingsDialog.setTabOrder(self.readBack_voice_radioButton, self.buttonBox)

    def retranslateUi(self, soloSessionSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        soloSessionSettingsDialog.setWindowTitle(_translate("soloSessionSettingsDialog", "Solo simulation options"))
        self.groupBox_10.setTitle(_translate("soloSessionSettingsDialog", "Traffic generator"))
        self.label_4.setText(_translate("soloSessionSettingsDialog", "0%"))
        self.label_3.setText(_translate("soloSessionSettingsDialog", "100%"))
        self.label_22.setText(_translate("soloSessionSettingsDialog", "Controlled aircraft count:"))
        self.maxSpawnDelay_minutes_edit.setSuffix(_translate("soloSessionSettingsDialog", " min"))
        self.label_19.setText(_translate("soloSessionSettingsDialog", "Spawn delay:"))
        self.minSpawnDelay_seconds_edit.setSuffix(_translate("soloSessionSettingsDialog", " s"))
        self.label_21.setText(_translate("soloSessionSettingsDialog", "to"))
        self.cpdlcConnections_label.setText(_translate("soloSessionSettingsDialog", "CPDLC connections:"))
        self.label.setText(_translate("soloSessionSettingsDialog", "Distractor level:"))
        self.airportMode_groupBox.setTitle(_translate("soloSessionSettingsDialog", "Airport mode objectives"))
        self.label_11.setText(_translate("soloSessionSettingsDialog", "ARR"))
        self.ARRvsDEP_edit.setToolTip(_translate("soloSessionSettingsDialog", "Arrival vs. departure balance"))
        self.label_18.setText(_translate("soloSessionSettingsDialog", "DEP"))
        self.label_16.setText(_translate("soloSessionSettingsDialog", "ILS"))
        self.ILSvsVisual_edit.setToolTip(_translate("soloSessionSettingsDialog", "ILS vs. visual approach balance\n"
"NB: Pilots might still be forced to request visual if they have no other choice."))
        self.label_17.setText(_translate("soloSessionSettingsDialog", "Visual"))
        self.groupBox_2.setTitle(_translate("soloSessionSettingsDialog", "Weather"))
        self.label_20.setText(_translate("soloSessionSettingsDialog", "Change interval:"))
        self.soloWeatherChangeInterval_edit.setSpecialValueText(_translate("soloSessionSettingsDialog", "No weather change"))
        self.soloWeatherChangeInterval_edit.setSuffix(_translate("soloSessionSettingsDialog", " min"))
        self.groupBox_8.setTitle(_translate("soloSessionSettingsDialog", "Instructions"))
        self.voiceInstr_off_radioButton.setToolTip(_translate("soloSessionSettingsDialog", "Mouse vector tool and handover drops will instruct selected callsign directly"))
        self.voiceInstr_off_radioButton.setText(_translate("soloSessionSettingsDialog", "Mouse only"))
        self.voiceInstr_on_radioButton.setToolTip(_translate("soloSessionSettingsDialog", "NB: Taxi instructions are not supported. Use mouse click-and-drag"))
        self.voiceInstr_on_radioButton.setText(_translate("soloSessionSettingsDialog", "Voice recognition"))
        self.groupBox_11.setTitle(_translate("soloSessionSettingsDialog", "Pilot communications"))
        self.readBack_off_radioButton.setText(_translate("soloSessionSettingsDialog", "Text only"))
        self.readBack_wilcoBeep_radioButton.setText(_translate("soloSessionSettingsDialog", "WILCO beeps"))
        self.readBack_voice_radioButton.setText(_translate("soloSessionSettingsDialog", "Voice synthesis"))

