
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_startFlightGearMPdialog(object):
    def setupUi(self, startFlightGearMPdialog):
        startFlightGearMPdialog.setObjectName("startFlightGearMPdialog")
        startFlightGearMPdialog.resize(341, 268)
        self.verticalLayout = QtWidgets.QVBoxLayout(startFlightGearMPdialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(startFlightGearMPdialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fgmsServer_info = QtWidgets.QLabel(self.groupBox)
        self.fgmsServer_info.setObjectName("fgmsServer_info")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgmsServer_info)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.callsign_edit = QtWidgets.QLineEdit(self.groupBox)
        self.callsign_edit.setMaxLength(7)
        self.callsign_edit.setObjectName("callsign_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.callsign_edit)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.clientPort_edit = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientPort_edit.sizePolicy().hasHeightForWidth())
        self.clientPort_edit.setSizePolicy(sizePolicy)
        self.clientPort_edit.setMaximum(65535)
        self.clientPort_edit.setObjectName("clientPort_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.clientPort_edit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(startFlightGearMPdialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ircTextChat_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ircTextChat_tickBox.setObjectName("ircTextChat_tickBox")
        self.verticalLayout_2.addWidget(self.ircTextChat_tickBox)
        self.orsx_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.orsx_tickBox.setObjectName("orsx_tickBox")
        self.verticalLayout_2.addWidget(self.orsx_tickBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(startFlightGearMPdialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_4.setBuddy(self.callsign_edit)
        self.label_3.setBuddy(self.clientPort_edit)

        self.retranslateUi(startFlightGearMPdialog)
        QtCore.QMetaObject.connectSlotsByName(startFlightGearMPdialog)
        startFlightGearMPdialog.setTabOrder(self.callsign_edit, self.clientPort_edit)
        startFlightGearMPdialog.setTabOrder(self.clientPort_edit, self.ircTextChat_tickBox)
        startFlightGearMPdialog.setTabOrder(self.ircTextChat_tickBox, self.orsx_tickBox)
        startFlightGearMPdialog.setTabOrder(self.orsx_tickBox, self.buttonBox)

    def retranslateUi(self, startFlightGearMPdialog):
        _translate = QtCore.QCoreApplication.translate
        startFlightGearMPdialog.setWindowTitle(_translate("startFlightGearMPdialog", "Connect to multi-player network"))
        self.groupBox.setTitle(_translate("startFlightGearMPdialog", "FGMS"))
        self.label.setText(_translate("startFlightGearMPdialog", "Connecting to:"))
        self.fgmsServer_info.setText(_translate("startFlightGearMPdialog", "###"))
        self.label_4.setText(_translate("startFlightGearMPdialog", "Callsign:"))
        self.callsign_edit.setToolTip(_translate("startFlightGearMPdialog", "Typically starts with a 4-letter ICAO code"))
        self.label_3.setText(_translate("startFlightGearMPdialog", "Local UDP port:"))
        self.clientPort_edit.setToolTip(_translate("startFlightGearMPdialog", "Choose a different port for each client if you are connecting more than one from the same host."))
        self.groupBox_2.setTitle(_translate("startFlightGearMPdialog", "ATC communication sub-systems"))
        self.ircTextChat_tickBox.setToolTip(_translate("startFlightGearMPdialog", "Enables full coordination with connected ATC-pie clients: strip exchange, ATC text chat, who-has requests"))
        self.ircTextChat_tickBox.setText(_translate("startFlightGearMPdialog", "IRC"))
        self.orsx_tickBox.setToolTip(_translate("startFlightGearMPdialog", "Enables strip exchange with OpenRadar clients"))
        self.orsx_tickBox.setText(_translate("startFlightGearMPdialog", "OpenRadar handover compatibility"))

