
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stripPane(object):
    def setupUi(self, stripPane):
        stripPane.setObjectName("stripPane")
        stripPane.resize(580, 255)
        self.verticalLayout = QtWidgets.QVBoxLayout(stripPane)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stacked_view_widget = QtWidgets.QStackedWidget(stripPane)
        self.stacked_view_widget.setObjectName("stacked_view_widget")
        self.tableView_page = QtWidgets.QWidget()
        self.tableView_page.setObjectName("tableView_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tableView_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stripRacks_view = StripTableView(self.tableView_page)
        self.stripRacks_view.setObjectName("stripRacks_view")
        self.verticalLayout_3.addWidget(self.stripRacks_view)
        self.stacked_view_widget.addWidget(self.tableView_page)
        self.tabView_page = QtWidgets.QWidget()
        self.tabView_page.setObjectName("tabView_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabView_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stripRacks_tabs = StripRackTabs(self.tabView_page)
        self.stripRacks_tabs.setMouseTracking(False)
        self.stripRacks_tabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.stripRacks_tabs.setMovable(True)
        self.stripRacks_tabs.setObjectName("stripRacks_tabs")
        self.verticalLayout_2.addWidget(self.stripRacks_tabs)
        self.stacked_view_widget.addWidget(self.tabView_page)
        self.verticalLayout.addWidget(self.stacked_view_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pull_menuButton = QtWidgets.QToolButton(stripPane)
        self.pull_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.pull_menuButton.setObjectName("pull_menuButton")
        self.horizontalLayout_2.addWidget(self.pull_menuButton)
        self.view_menuButton = QtWidgets.QToolButton(stripPane)
        self.view_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.view_menuButton.setObjectName("view_menuButton")
        self.horizontalLayout_2.addWidget(self.view_menuButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.deleteStrip_button = QtWidgets.QToolButton(stripPane)
        self.deleteStrip_button.setObjectName("deleteStrip_button")
        self.horizontalLayout_2.addWidget(self.deleteStrip_button)
        self.frame = QtWidgets.QFrame(stripPane)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shelf_button = ShelfButtonWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy)
        self.shelf_button.setMinimumSize(QtCore.QSize(50, 0))
        self.shelf_button.setObjectName("shelf_button")
        self.horizontalLayout.addWidget(self.shelf_button)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(stripPane)
        self.stacked_view_widget.setCurrentIndex(0)
        self.stripRacks_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(stripPane)

    def retranslateUi(self, stripPane):
        _translate = QtCore.QCoreApplication.translate
        stripPane.setWindowTitle(_translate("stripPane", "Strip racks"))
        self.pull_menuButton.setToolTip(_translate("stripPane", "Pull details to strip"))
        self.pull_menuButton.setText(_translate("stripPane", "Pull"))
        self.view_menuButton.setText(_translate("stripPane", "Opts"))
        self.deleteStrip_button.setToolTip(_translate("stripPane", "Delete strip"))
        self.deleteStrip_button.setText(_translate("stripPane", "- strip"))

from gui.widgets.basicWidgets import ShelfButtonWidget
from gui.widgets.stripView import StripRackTabs, StripTableView
