from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_systemSettingsDialog(object):
    def setupUi(self, systemSettingsDialog):
        systemSettingsDialog.setObjectName("systemSettingsDialog")
        systemSettingsDialog.resize(672, 455)
        self.verticalLayout = QtWidgets.QVBoxLayout(systemSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_tabs = QtWidgets.QTabWidget(systemSettingsDialog)
        self.settings_tabs.setObjectName("settings_tabs")
        self.towerView_page = QtWidgets.QWidget()
        self.towerView_page.setObjectName("towerView_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.towerView_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.towerView_internal_radioButton = QtWidgets.QRadioButton(self.towerView_page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.towerView_internal_radioButton.setFont(font)
        self.towerView_internal_radioButton.setObjectName("towerView_internal_radioButton")
        self.verticalLayout_2.addWidget(self.towerView_internal_radioButton)
        self.internalTowerView_widget = QtWidgets.QWidget(self.towerView_page)
        self.internalTowerView_widget.setEnabled(False)
        self.internalTowerView_widget.setObjectName("internalTowerView_widget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.internalTowerView_widget)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(30, 0, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.internalTowerView_widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fgCommand_edit = QtWidgets.QLineEdit(self.internalTowerView_widget)
        self.fgCommand_edit.setObjectName("fgCommand_edit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgCommand_edit)
        self.label_5 = QtWidgets.QLabel(self.internalTowerView_widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fgRootDir_edit = QtWidgets.QLineEdit(self.internalTowerView_widget)
        self.fgRootDir_edit.setObjectName("fgRootDir_edit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgRootDir_edit)
        self.label_4 = QtWidgets.QLabel(self.internalTowerView_widget)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_26 = QtWidgets.QLabel(self.internalTowerView_widget)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.fgSceneryDir_edit = QtWidgets.QLineEdit(self.internalTowerView_widget)
        self.fgSceneryDir_edit.setObjectName("fgSceneryDir_edit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgSceneryDir_edit)
        self.fgAircraftDir_edit = QtWidgets.QLineEdit(self.internalTowerView_widget)
        self.fgAircraftDir_edit.setObjectName("fgAircraftDir_edit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgAircraftDir_edit)
        self.verticalLayout_2.addWidget(self.internalTowerView_widget)
        self.towerView_external_radioButton = QtWidgets.QRadioButton(self.towerView_page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.towerView_external_radioButton.setFont(font)
        self.towerView_external_radioButton.setObjectName("towerView_external_radioButton")
        self.verticalLayout_2.addWidget(self.towerView_external_radioButton)
        self.externalTowerView_widget = QtWidgets.QWidget(self.towerView_page)
        self.externalTowerView_widget.setEnabled(False)
        self.externalTowerView_widget.setObjectName("externalTowerView_widget")
        self.formLayout = QtWidgets.QFormLayout(self.externalTowerView_widget)
        self.formLayout.setContentsMargins(30, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_15 = QtWidgets.QLabel(self.externalTowerView_widget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.externalTowerViewerHost_edit = QtWidgets.QLineEdit(self.externalTowerView_widget)
        self.externalTowerViewerHost_edit.setObjectName("externalTowerViewerHost_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.externalTowerViewerHost_edit)
        self.label_19 = QtWidgets.QLabel(self.externalTowerView_widget)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.produceExtViewerCmd_button = QtWidgets.QToolButton(self.externalTowerView_widget)
        self.produceExtViewerCmd_button.setObjectName("produceExtViewerCmd_button")
        self.horizontalLayout.addWidget(self.produceExtViewerCmd_button)
        self.label_21 = QtWidgets.QLabel(self.externalTowerView_widget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.externalTowerView_widget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.towerView_page)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.towerView_fgmsPort_edit = QtWidgets.QSpinBox(self.groupBox)
        self.towerView_fgmsPort_edit.setMaximum(65535)
        self.towerView_fgmsPort_edit.setObjectName("towerView_fgmsPort_edit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.towerView_fgmsPort_edit)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.towerView_telnetPort_edit = QtWidgets.QSpinBox(self.groupBox)
        self.towerView_telnetPort_edit.setMaximum(65535)
        self.towerView_telnetPort_edit.setObjectName("towerView_telnetPort_edit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.towerView_telnetPort_edit)
        self.horizontalLayout_5.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.settings_tabs.addTab(self.towerView_page, "")
        self.fgcom_page = QtWidgets.QWidget()
        self.fgcom_page.setObjectName("fgcom_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fgcom_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.FGCom_groupBox = QtWidgets.QGroupBox(self.fgcom_page)
        self.FGCom_groupBox.setObjectName("FGCom_groupBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.FGCom_groupBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_14 = QtWidgets.QLabel(self.FGCom_groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.fgcomExe_edit = QtWidgets.QLineEdit(self.FGCom_groupBox)
        self.fgcomExe_edit.setObjectName("fgcomExe_edit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgcomExe_edit)
        self.label = QtWidgets.QLabel(self.FGCom_groupBox)
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fgcomServer_edit = QtWidgets.QLineEdit(self.FGCom_groupBox)
        self.fgcomServer_edit.setObjectName("fgcomServer_edit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgcomServer_edit)
        self.line_3 = QtWidgets.QFrame(self.FGCom_groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.label_9 = QtWidgets.QLabel(self.FGCom_groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fgcomReservedPort_edit = QtWidgets.QSpinBox(self.FGCom_groupBox)
        self.fgcomReservedPort_edit.setMaximum(65535)
        self.fgcomReservedPort_edit.setObjectName("fgcomReservedPort_edit")
        self.horizontalLayout_4.addWidget(self.fgcomReservedPort_edit)
        self.label_12 = QtWidgets.QLabel(self.FGCom_groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.formLayout_5.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.FGCom_groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.fgcomRadioBoxPorts_edit = QtWidgets.QLineEdit(self.FGCom_groupBox)
        self.fgcomRadioBoxPorts_edit.setObjectName("fgcomRadioBoxPorts_edit")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fgcomRadioBoxPorts_edit)
        self.verticalLayout_4.addWidget(self.FGCom_groupBox)
        self.settings_tabs.addTab(self.fgcom_page, "")
        self.flightgearMP_page = QtWidgets.QWidget()
        self.flightgearMP_page.setObjectName("flightgearMP_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.flightgearMP_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FG_network_groupBox = QtWidgets.QGroupBox(self.flightgearMP_page)
        self.FG_network_groupBox.setObjectName("FG_network_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.FG_network_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_31 = QtWidgets.QLabel(self.FG_network_groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 2, 3, 1, 1)
        self.ircServerPort_edit = QtWidgets.QSpinBox(self.FG_network_groupBox)
        self.ircServerPort_edit.setMaximum(65535)
        self.ircServerPort_edit.setObjectName("ircServerPort_edit")
        self.gridLayout_2.addWidget(self.ircServerPort_edit, 2, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 6, 1, 1)
        self.fgmsServerHost_edit = QtWidgets.QLineEdit(self.FG_network_groupBox)
        self.fgmsServerHost_edit.setObjectName("fgmsServerHost_edit")
        self.gridLayout_2.addWidget(self.fgmsServerHost_edit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.fgmsServerPort_edit = QtWidgets.QSpinBox(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgmsServerPort_edit.sizePolicy().hasHeightForWidth())
        self.fgmsServerPort_edit.setSizePolicy(sizePolicy)
        self.fgmsServerPort_edit.setMaximum(65535)
        self.fgmsServerPort_edit.setObjectName("fgmsServerPort_edit")
        self.gridLayout_2.addWidget(self.fgmsServerPort_edit, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.FG_network_groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.orsxHandoverRange_edit = QtWidgets.QSpinBox(self.FG_network_groupBox)
        self.orsxHandoverRange_edit.setMaximum(1000)
        self.orsxHandoverRange_edit.setSingleStep(10)
        self.orsxHandoverRange_edit.setObjectName("orsxHandoverRange_edit")
        self.gridLayout_2.addWidget(self.orsxHandoverRange_edit, 3, 7, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.FG_network_groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 0, 1, 1)
        self.nickname_edit = QtWidgets.QLineEdit(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickname_edit.sizePolicy().hasHeightForWidth())
        self.nickname_edit.setSizePolicy(sizePolicy)
        self.nickname_edit.setObjectName("nickname_edit")
        self.gridLayout_2.addWidget(self.nickname_edit, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.FG_network_groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 0, 1, 1)
        self.ircServerHost_edit = QtWidgets.QLineEdit(self.FG_network_groupBox)
        self.ircServerHost_edit.setObjectName("ircServerHost_edit")
        self.gridLayout_2.addWidget(self.ircServerHost_edit, 2, 1, 1, 1)
        self.ircChannel_edit = QtWidgets.QLineEdit(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ircChannel_edit.sizePolicy().hasHeightForWidth())
        self.ircChannel_edit.setSizePolicy(sizePolicy)
        self.ircChannel_edit.setObjectName("ircChannel_edit")
        self.gridLayout_2.addWidget(self.ircChannel_edit, 2, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.FG_network_groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.orsxServer_edit = QtWidgets.QLineEdit(self.FG_network_groupBox)
        self.orsxServer_edit.setObjectName("orsxServer_edit")
        self.gridLayout_2.addWidget(self.orsxServer_edit, 3, 1, 1, 4)
        self.label_27 = QtWidgets.QLabel(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 3, 6, 1, 1)
        self.fgmsLegacyProtocol_tickBox = QtWidgets.QCheckBox(self.FG_network_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgmsLegacyProtocol_tickBox.sizePolicy().hasHeightForWidth())
        self.fgmsLegacyProtocol_tickBox.setSizePolicy(sizePolicy)
        self.fgmsLegacyProtocol_tickBox.setObjectName("fgmsLegacyProtocol_tickBox")
        self.gridLayout_2.addWidget(self.fgmsLegacyProtocol_tickBox, 0, 6, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.FG_network_groupBox)
        self.FG_lenny64_groupBox = QtWidgets.QGroupBox(self.flightgearMP_page)
        self.FG_lenny64_groupBox.setObjectName("FG_lenny64_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.FG_lenny64_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.FG_lenny64_groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.FG_lenny64_groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 0, 1, 1)
        self.lennyAccountEmail_edit = QtWidgets.QLineEdit(self.FG_lenny64_groupBox)
        self.lennyAccountEmail_edit.setObjectName("lennyAccountEmail_edit")
        self.gridLayout.addWidget(self.lennyAccountEmail_edit, 0, 1, 1, 1)
        self.passwordChange_info = QtWidgets.QLabel(self.FG_lenny64_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwordChange_info.setFont(font)
        self.passwordChange_info.setText("")
        self.passwordChange_info.setObjectName("passwordChange_info")
        self.gridLayout.addWidget(self.passwordChange_info, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.FG_lenny64_groupBox)
        self.label_25.setOpenExternalLinks(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 3, 1, 1)
        self.lennyPassword_edit = QtWidgets.QLineEdit(self.FG_lenny64_groupBox)
        self.lennyPassword_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lennyPassword_edit.setObjectName("lennyPassword_edit")
        self.gridLayout.addWidget(self.lennyPassword_edit, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.FG_lenny64_groupBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.flightgearMP_page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.FPLupdateInterval_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.FPLupdateInterval_edit.setObjectName("FPLupdateInterval_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FPLupdateInterval_edit)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.METARupdateInterval_edit = QtWidgets.QSpinBox(self.groupBox_3)
        self.METARupdateInterval_edit.setObjectName("METARupdateInterval_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.METARupdateInterval_edit)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.settings_tabs.addTab(self.flightgearMP_page, "")
        self.solo_page = QtWidgets.QWidget()
        self.solo_page.setObjectName("solo_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.solo_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.solo_page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 2)
        self.soloAircraftTypes_edit = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.soloAircraftTypes_edit.setTabChangesFocus(True)
        self.soloAircraftTypes_edit.setBackgroundVisible(True)
        self.soloAircraftTypes_edit.setObjectName("soloAircraftTypes_edit")
        self.gridLayout_4.addWidget(self.soloAircraftTypes_edit, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_32.setFont(font)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.restrictAirlineChoiceToLiveries_tickBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.restrictAirlineChoiceToLiveries_tickBox.setObjectName("restrictAirlineChoiceToLiveries_tickBox")
        self.verticalLayout_5.addWidget(self.restrictAirlineChoiceToLiveries_tickBox)
        self.preferEntryExitAirports_tickBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.preferEntryExitAirports_tickBox.setObjectName("preferEntryExitAirports_tickBox")
        self.verticalLayout_5.addWidget(self.preferEntryExitAirports_tickBox)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.SR_groupBox = QtWidgets.QGroupBox(self.solo_page)
        self.SR_groupBox.setObjectName("SR_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SR_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.SR_groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.sphinxAcousticModel_edit = QtWidgets.QLineEdit(self.SR_groupBox)
        self.sphinxAcousticModel_edit.setObjectName("sphinxAcousticModel_edit")
        self.gridLayout_5.addWidget(self.sphinxAcousticModel_edit, 0, 1, 1, 1)
        self.browseForSphinxAcousticModel_button = QtWidgets.QToolButton(self.SR_groupBox)
        self.browseForSphinxAcousticModel_button.setObjectName("browseForSphinxAcousticModel_button")
        self.gridLayout_5.addWidget(self.browseForSphinxAcousticModel_button, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.SR_groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 1, 0, 1, 1)
        self.audioDeviceIndex_edit = QtWidgets.QSpinBox(self.SR_groupBox)
        self.audioDeviceIndex_edit.setMinimum(-1)
        self.audioDeviceIndex_edit.setObjectName("audioDeviceIndex_edit")
        self.gridLayout_5.addWidget(self.audioDeviceIndex_edit, 1, 1, 1, 1)
        self.audioDeviceInfo_button = QtWidgets.QToolButton(self.SR_groupBox)
        self.audioDeviceInfo_button.setObjectName("audioDeviceInfo_button")
        self.gridLayout_5.addWidget(self.audioDeviceInfo_button, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.SR_groupBox)
        self.settings_tabs.addTab(self.solo_page, "")
        self.verticalLayout.addWidget(self.settings_tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(systemSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.buttonBox.raise_()
        self.settings_tabs.raise_()
        self.label_2.setBuddy(self.fgCommand_edit)
        self.label_5.setBuddy(self.fgRootDir_edit)
        self.label_4.setBuddy(self.fgSceneryDir_edit)
        self.label_26.setBuddy(self.fgAircraftDir_edit)
        self.label_15.setBuddy(self.externalTowerViewerHost_edit)
        self.label_19.setBuddy(self.produceExtViewerCmd_button)
        self.label_16.setBuddy(self.towerView_fgmsPort_edit)
        self.label_18.setBuddy(self.towerView_telnetPort_edit)
        self.label_14.setBuddy(self.fgcomExe_edit)
        self.label.setBuddy(self.fgcomServer_edit)
        self.label_9.setBuddy(self.fgcomReservedPort_edit)
        self.label_13.setBuddy(self.fgcomRadioBoxPorts_edit)
        self.label_31.setBuddy(self.ircServerPort_edit)
        self.label_30.setBuddy(self.ircChannel_edit)
        self.label_6.setBuddy(self.fgmsServerPort_edit)
        self.label_3.setBuddy(self.fgmsServerHost_edit)
        self.label_29.setBuddy(self.nickname_edit)
        self.label_20.setBuddy(self.ircServerHost_edit)
        self.label_11.setBuddy(self.orsxServer_edit)
        self.label_27.setBuddy(self.orsxHandoverRange_edit)
        self.label_8.setBuddy(self.lennyPassword_edit)
        self.label_24.setBuddy(self.lennyAccountEmail_edit)
        self.label_25.setBuddy(self.lennyAccountEmail_edit)
        self.label_7.setBuddy(self.FPLupdateInterval_edit)
        self.label_10.setBuddy(self.METARupdateInterval_edit)
        self.label_23.setBuddy(self.soloAircraftTypes_edit)
        self.label_22.setBuddy(self.sphinxAcousticModel_edit)
        self.label_28.setBuddy(self.audioDeviceIndex_edit)

        self.retranslateUi(systemSettingsDialog)
        self.settings_tabs.setCurrentIndex(0)
        self.buttonBox.rejected.connect(systemSettingsDialog.reject)
        self.towerView_internal_radioButton.toggled['bool'].connect(self.internalTowerView_widget.setEnabled)
        self.towerView_external_radioButton.toggled['bool'].connect(self.externalTowerView_widget.setEnabled)
        self.towerView_internal_radioButton.toggled['bool'].connect(self.fgCommand_edit.setFocus)
        self.towerView_external_radioButton.toggled['bool'].connect(self.externalTowerViewerHost_edit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(systemSettingsDialog)
        systemSettingsDialog.setTabOrder(self.settings_tabs, self.towerView_internal_radioButton)
        systemSettingsDialog.setTabOrder(self.towerView_internal_radioButton, self.fgCommand_edit)
        systemSettingsDialog.setTabOrder(self.fgCommand_edit, self.fgRootDir_edit)
        systemSettingsDialog.setTabOrder(self.fgRootDir_edit, self.fgAircraftDir_edit)
        systemSettingsDialog.setTabOrder(self.fgAircraftDir_edit, self.fgSceneryDir_edit)
        systemSettingsDialog.setTabOrder(self.fgSceneryDir_edit, self.towerView_external_radioButton)
        systemSettingsDialog.setTabOrder(self.towerView_external_radioButton, self.externalTowerViewerHost_edit)
        systemSettingsDialog.setTabOrder(self.externalTowerViewerHost_edit, self.produceExtViewerCmd_button)
        systemSettingsDialog.setTabOrder(self.produceExtViewerCmd_button, self.towerView_fgmsPort_edit)
        systemSettingsDialog.setTabOrder(self.towerView_fgmsPort_edit, self.towerView_telnetPort_edit)
        systemSettingsDialog.setTabOrder(self.towerView_telnetPort_edit, self.fgcomExe_edit)
        systemSettingsDialog.setTabOrder(self.fgcomExe_edit, self.fgcomServer_edit)
        systemSettingsDialog.setTabOrder(self.fgcomServer_edit, self.fgcomReservedPort_edit)
        systemSettingsDialog.setTabOrder(self.fgcomReservedPort_edit, self.fgcomRadioBoxPorts_edit)
        systemSettingsDialog.setTabOrder(self.fgcomRadioBoxPorts_edit, self.fgmsServerHost_edit)
        systemSettingsDialog.setTabOrder(self.fgmsServerHost_edit, self.fgmsServerPort_edit)
        systemSettingsDialog.setTabOrder(self.fgmsServerPort_edit, self.fgmsLegacyProtocol_tickBox)
        systemSettingsDialog.setTabOrder(self.fgmsLegacyProtocol_tickBox, self.nickname_edit)
        systemSettingsDialog.setTabOrder(self.nickname_edit, self.ircServerHost_edit)
        systemSettingsDialog.setTabOrder(self.ircServerHost_edit, self.ircServerPort_edit)
        systemSettingsDialog.setTabOrder(self.ircServerPort_edit, self.ircChannel_edit)
        systemSettingsDialog.setTabOrder(self.ircChannel_edit, self.orsxServer_edit)
        systemSettingsDialog.setTabOrder(self.orsxServer_edit, self.orsxHandoverRange_edit)
        systemSettingsDialog.setTabOrder(self.orsxHandoverRange_edit, self.lennyAccountEmail_edit)
        systemSettingsDialog.setTabOrder(self.lennyAccountEmail_edit, self.lennyPassword_edit)
        systemSettingsDialog.setTabOrder(self.lennyPassword_edit, self.FPLupdateInterval_edit)
        systemSettingsDialog.setTabOrder(self.FPLupdateInterval_edit, self.METARupdateInterval_edit)
        systemSettingsDialog.setTabOrder(self.METARupdateInterval_edit, self.soloAircraftTypes_edit)
        systemSettingsDialog.setTabOrder(self.soloAircraftTypes_edit, self.restrictAirlineChoiceToLiveries_tickBox)
        systemSettingsDialog.setTabOrder(self.restrictAirlineChoiceToLiveries_tickBox, self.preferEntryExitAirports_tickBox)
        systemSettingsDialog.setTabOrder(self.preferEntryExitAirports_tickBox, self.sphinxAcousticModel_edit)
        systemSettingsDialog.setTabOrder(self.sphinxAcousticModel_edit, self.browseForSphinxAcousticModel_button)
        systemSettingsDialog.setTabOrder(self.browseForSphinxAcousticModel_button, self.audioDeviceIndex_edit)
        systemSettingsDialog.setTabOrder(self.audioDeviceIndex_edit, self.audioDeviceInfo_button)
        systemSettingsDialog.setTabOrder(self.audioDeviceInfo_button, self.buttonBox)

    def retranslateUi(self, systemSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        systemSettingsDialog.setWindowTitle(_translate("systemSettingsDialog", "System settings"))
        self.towerView_internal_radioButton.setText(_translate("systemSettingsDialog", "Start internally (child process)"))
        self.label_2.setText(_translate("systemSettingsDialog", "FlightGear command:"))
        self.label_5.setText(_translate("systemSettingsDialog", "FG root directory:"))
        self.fgRootDir_edit.setPlaceholderText(_translate("systemSettingsDialog", "FlightGear default"))
        self.label_4.setText(_translate("systemSettingsDialog", "Scenery directory:"))
        self.label_26.setText(_translate("systemSettingsDialog", "Aircraft directory:"))
        self.fgSceneryDir_edit.setPlaceholderText(_translate("systemSettingsDialog", "FlightGear default"))
        self.fgAircraftDir_edit.setPlaceholderText(_translate("systemSettingsDialog", "FlightGear default"))
        self.towerView_external_radioButton.setText(_translate("systemSettingsDialog", "Connect to external instance"))
        self.label_15.setText(_translate("systemSettingsDialog", "Running host:"))
        self.label_19.setText(_translate("systemSettingsDialog", "FG options hint:"))
        self.produceExtViewerCmd_button.setText(_translate("systemSettingsDialog", "Show..."))
        self.label_21.setText(_translate("systemSettingsDialog", "(options to start an external viewer at current viewpoint)"))
        self.groupBox.setTitle(_translate("systemSettingsDialog", "IPC setup"))
        self.label_16.setText(_translate("systemSettingsDialog", "FGMS destination port (UDP):"))
        self.label_18.setText(_translate("systemSettingsDialog", "Telnet connection port (TCP):"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.towerView_page), _translate("systemSettingsDialog", "Tower view"))
        self.FGCom_groupBox.setTitle(_translate("systemSettingsDialog", "Internal FGCom client options"))
        self.label_14.setText(_translate("systemSettingsDialog", "Executable file:"))
        self.fgcomExe_edit.setToolTip(_translate("systemSettingsDialog", "Relative or absolute path to FGCom executable. Also defines working directoy for started process."))
        self.label.setText(_translate("systemSettingsDialog", "Server:"))
        self.label_9.setText(_translate("systemSettingsDialog", "Reserved port:"))
        self.label_12.setText(_translate("systemSettingsDialog", "(used for echo testing and ATIS recording)"))
        self.label_13.setText(_translate("systemSettingsDialog", "Radio box ports:"))
        self.fgcomRadioBoxPorts_edit.setToolTip(_translate("systemSettingsDialog", "Comma-separated list, leave blank for external FGCom use only"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.fgcom_page), _translate("systemSettingsDialog", "FGCom radio"))
        self.FG_network_groupBox.setTitle(_translate("systemSettingsDialog", "Network configuration"))
        self.label_31.setText(_translate("systemSettingsDialog", "Port:"))
        self.label_30.setText(_translate("systemSettingsDialog", "Channel:"))
        self.label_6.setText(_translate("systemSettingsDialog", "Port:"))
        self.label_3.setText(_translate("systemSettingsDialog", "FGMS host:"))
        self.orsxHandoverRange_edit.setToolTip(_translate("systemSettingsDialog", "Maximum distance for handovers through the OpenRadar service"))
        self.orsxHandoverRange_edit.setSpecialValueText(_translate("systemSettingsDialog", "Same as radar"))
        self.orsxHandoverRange_edit.setSuffix(_translate("systemSettingsDialog", " NM"))
        self.label_29.setText(_translate("systemSettingsDialog", "Social name:"))
        self.nickname_edit.setToolTip(_translate("systemSettingsDialog", "Real/social name on network"))
        self.label_20.setText(_translate("systemSettingsDialog", "IRC server:"))
        self.ircServerHost_edit.setToolTip(_translate("systemSettingsDialog", "Enables strip exchange and ATC text chat with other ATC-pie clients"))
        self.label_11.setText(_translate("systemSettingsDialog", "OpenRadar server:"))
        self.orsxServer_edit.setToolTip(_translate("systemSettingsDialog", "Enables strip exchange with OpenRadar clients"))
        self.label_27.setText(_translate("systemSettingsDialog", "Range:"))
        self.fgmsLegacyProtocol_tickBox.setToolTip(_translate("systemSettingsDialog", "Less efficient protocol but allows pre-2017.2 clients to read your text messages"))
        self.fgmsLegacyProtocol_tickBox.setText(_translate("systemSettingsDialog", "Legacy protocol"))
        self.FG_lenny64_groupBox.setTitle(_translate("systemSettingsDialog", "Lenny64 identification"))
        self.label_8.setText(_translate("systemSettingsDialog", "Password:"))
        self.label_24.setText(_translate("systemSettingsDialog", "Account email:"))
        self.lennyAccountEmail_edit.setPlaceholderText(_translate("systemSettingsDialog", "FPL filing and editing disabled if blank"))
        self.label_25.setText(_translate("systemSettingsDialog", "<html><head/><body><p>(<a href=\"http://flightgear-atc.alwaysdata.net/subscribe.php5\"><span style=\" text-decoration: underline; color:#0000ff;\">create</span></a> your ATC dashboard)</p></body></html>"))
        self.groupBox_3.setTitle(_translate("systemSettingsDialog", "Online look-up intervals"))
        self.label_7.setText(_translate("systemSettingsDialog", "Flight plans:"))
        self.FPLupdateInterval_edit.setSpecialValueText(_translate("systemSettingsDialog", "Manual checks only"))
        self.FPLupdateInterval_edit.setSuffix(_translate("systemSettingsDialog", " min"))
        self.label_10.setText(_translate("systemSettingsDialog", "Weather:"))
        self.METARupdateInterval_edit.setSpecialValueText(_translate("systemSettingsDialog", "Manual checks only"))
        self.METARupdateInterval_edit.setSuffix(_translate("systemSettingsDialog", " min"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.flightgearMP_page), _translate("systemSettingsDialog", "FlightGear multi-player"))
        self.groupBox_6.setTitle(_translate("systemSettingsDialog", "Traffic generator"))
        self.label_23.setText(_translate("systemSettingsDialog", "ACFT types to spawn (one type designator per line):"))
        self.label_32.setText(_translate("systemSettingsDialog", "NB: Types unsuitable for a chosen location (e.g. with no runway to land on), or missing information (e.g. cruise speed) will be ignored."))
        self.restrictAirlineChoiceToLiveries_tickBox.setToolTip(_translate("systemSettingsDialog", "Edit choice in \"resources/acft/icao2fgfs\""))
        self.restrictAirlineChoiceToLiveries_tickBox.setText(_translate("systemSettingsDialog", "Restrict commercial airline choice in AD mode to available liveries if any are listed for the type"))
        self.preferEntryExitAirports_tickBox.setToolTip(_translate("systemSettingsDialog", "Better routes on strips, but more repetitive if only few choices given in \"resources/nav/AD-entry-exit\""))
        self.preferEntryExitAirports_tickBox.setText(_translate("systemSettingsDialog", "Prefer airports with known entry/exit points for routes from/to present location"))
        self.SR_groupBox.setTitle(_translate("systemSettingsDialog", "Voice instruction recognition"))
        self.label_22.setText(_translate("systemSettingsDialog", "Sphinx acoustic model:"))
        self.sphinxAcousticModel_edit.setToolTip(_translate("systemSettingsDialog", "Directory entry"))
        self.sphinxAcousticModel_edit.setPlaceholderText(_translate("systemSettingsDialog", "Default \"en-us\" model"))
        self.browseForSphinxAcousticModel_button.setToolTip(_translate("systemSettingsDialog", "Browse"))
        self.browseForSphinxAcousticModel_button.setText(_translate("systemSettingsDialog", "..."))
        self.label_28.setText(_translate("systemSettingsDialog", "Input device index:"))
        self.audioDeviceIndex_edit.setSpecialValueText(_translate("systemSettingsDialog", "PyAudio default"))
        self.audioDeviceInfo_button.setToolTip(_translate("systemSettingsDialog", "Information on devices"))
        self.audioDeviceInfo_button.setText(_translate("systemSettingsDialog", "?"))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.solo_page), _translate("systemSettingsDialog", "Solo sessions"))

