from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_unitConversionWidget(object):
    def setupUi(self, unitConversionWidget):
        unitConversionWidget.setObjectName("unitConversionWidget")
        unitConversionWidget.resize(247, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(unitConversionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(unitConversionWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizDist_NM_edit = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.horizDist_NM_edit.setDecimals(1)
        self.horizDist_NM_edit.setMaximum(25000.0)
        self.horizDist_NM_edit.setObjectName("horizDist_NM_edit")
        self.gridLayout_3.addWidget(self.horizDist_NM_edit, 0, 0, 1, 1)
        self.horizDist_mi_edit = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.horizDist_mi_edit.setDecimals(1)
        self.horizDist_mi_edit.setObjectName("horizDist_mi_edit")
        self.gridLayout_3.addWidget(self.horizDist_mi_edit, 1, 0, 1, 1)
        self.horizDist_km_edit = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.horizDist_km_edit.setDecimals(1)
        self.horizDist_km_edit.setObjectName("horizDist_km_edit")
        self.gridLayout_3.addWidget(self.horizDist_km_edit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(unitConversionWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.alt_m_edit = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.alt_m_edit.setDecimals(1)
        self.alt_m_edit.setObjectName("alt_m_edit")
        self.gridLayout_4.addWidget(self.alt_m_edit, 0, 1, 1, 1)
        self.alt_ft_edit = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.alt_ft_edit.setDecimals(1)
        self.alt_ft_edit.setMaximum(50000.0)
        self.alt_ft_edit.setObjectName("alt_ft_edit")
        self.gridLayout_4.addWidget(self.alt_ft_edit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(unitConversionWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speed_mps_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.speed_mps_edit.setDecimals(1)
        self.speed_mps_edit.setObjectName("speed_mps_edit")
        self.gridLayout_2.addWidget(self.speed_mps_edit, 1, 1, 1, 1)
        self.speed_mph_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.speed_mph_edit.setDecimals(1)
        self.speed_mph_edit.setObjectName("speed_mph_edit")
        self.gridLayout_2.addWidget(self.speed_mph_edit, 1, 0, 1, 1)
        self.speed_kmh_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.speed_kmh_edit.setDecimals(1)
        self.speed_kmh_edit.setObjectName("speed_kmh_edit")
        self.gridLayout_2.addWidget(self.speed_kmh_edit, 0, 1, 1, 1)
        self.speed_kt_edit = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.speed_kt_edit.setDecimals(1)
        self.speed_kt_edit.setMaximum(2000.0)
        self.speed_kt_edit.setObjectName("speed_kt_edit")
        self.gridLayout_2.addWidget(self.speed_kt_edit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(unitConversionWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.temp_C_edit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.temp_C_edit.setDecimals(1)
        self.temp_C_edit.setMinimum(-100.0)
        self.temp_C_edit.setObjectName("temp_C_edit")
        self.gridLayout_5.addWidget(self.temp_C_edit, 0, 0, 1, 1)
        self.temp_F_edit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.temp_F_edit.setDecimals(1)
        self.temp_F_edit.setObjectName("temp_F_edit")
        self.gridLayout_5.addWidget(self.temp_F_edit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(unitConversionWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.pressure_inHg_edit = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.pressure_inHg_edit.setObjectName("pressure_inHg_edit")
        self.gridLayout.addWidget(self.pressure_inHg_edit, 0, 1, 1, 1)
        self.pressure_hPa_edit = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.pressure_hPa_edit.setDecimals(1)
        self.pressure_hPa_edit.setMinimum(950.0)
        self.pressure_hPa_edit.setMaximum(1050.0)
        self.pressure_hPa_edit.setObjectName("pressure_hPa_edit")
        self.gridLayout.addWidget(self.pressure_hPa_edit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(unitConversionWidget)
        self.close_button.setObjectName("close_button")
        self.verticalLayout.addWidget(self.close_button)

        self.retranslateUi(unitConversionWidget)
        self.close_button.clicked.connect(unitConversionWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(unitConversionWidget)
        unitConversionWidget.setTabOrder(self.horizDist_NM_edit, self.horizDist_km_edit)
        unitConversionWidget.setTabOrder(self.horizDist_km_edit, self.horizDist_mi_edit)
        unitConversionWidget.setTabOrder(self.horizDist_mi_edit, self.alt_ft_edit)
        unitConversionWidget.setTabOrder(self.alt_ft_edit, self.alt_m_edit)
        unitConversionWidget.setTabOrder(self.alt_m_edit, self.speed_kt_edit)
        unitConversionWidget.setTabOrder(self.speed_kt_edit, self.speed_kmh_edit)
        unitConversionWidget.setTabOrder(self.speed_kmh_edit, self.speed_mph_edit)
        unitConversionWidget.setTabOrder(self.speed_mph_edit, self.speed_mps_edit)
        unitConversionWidget.setTabOrder(self.speed_mps_edit, self.temp_C_edit)
        unitConversionWidget.setTabOrder(self.temp_C_edit, self.temp_F_edit)
        unitConversionWidget.setTabOrder(self.temp_F_edit, self.pressure_hPa_edit)
        unitConversionWidget.setTabOrder(self.pressure_hPa_edit, self.pressure_inHg_edit)
        unitConversionWidget.setTabOrder(self.pressure_inHg_edit, self.close_button)

    def retranslateUi(self, unitConversionWidget):
        _translate = QtCore.QCoreApplication.translate
        unitConversionWidget.setWindowTitle(_translate("unitConversionWidget", "Unit conversion tool"))
        self.groupBox_5.setToolTip(_translate("unitConversionWidget", "Synchronises with radar measuring tool (distance) and primary METAR station updates (prevailing visibility)"))
        self.groupBox_5.setTitle(_translate("unitConversionWidget", "Horiz. distances"))
        self.horizDist_NM_edit.setToolTip(_translate("unitConversionWidget", "Nautical miles"))
        self.horizDist_NM_edit.setSuffix(_translate("unitConversionWidget", " NM"))
        self.horizDist_mi_edit.setToolTip(_translate("unitConversionWidget", "Statute miles"))
        self.horizDist_mi_edit.setSuffix(_translate("unitConversionWidget", " mi"))
        self.horizDist_km_edit.setToolTip(_translate("unitConversionWidget", "Kilometres"))
        self.horizDist_km_edit.setSuffix(_translate("unitConversionWidget", " km"))
        self.groupBox_4.setToolTip(_translate("unitConversionWidget", "Synchronises with radar contact selection change (alt. AMSL or FL if over TA)"))
        self.groupBox_4.setTitle(_translate("unitConversionWidget", "Altitudes/heights"))
        self.alt_m_edit.setToolTip(_translate("unitConversionWidget", "Metres"))
        self.alt_m_edit.setSuffix(_translate("unitConversionWidget", " m"))
        self.alt_ft_edit.setToolTip(_translate("unitConversionWidget", "Feet"))
        self.alt_ft_edit.setSuffix(_translate("unitConversionWidget", " ft"))
        self.groupBox_3.setToolTip(_translate("unitConversionWidget", "Synchronises with radar contact selection change (ground speed) and primary METAR station updates (wind speed)"))
        self.groupBox_3.setTitle(_translate("unitConversionWidget", "Speeds"))
        self.speed_mps_edit.setToolTip(_translate("unitConversionWidget", "Metres per second"))
        self.speed_mps_edit.setSuffix(_translate("unitConversionWidget", " m/s"))
        self.speed_mph_edit.setToolTip(_translate("unitConversionWidget", "Miles per hour"))
        self.speed_mph_edit.setSuffix(_translate("unitConversionWidget", " mph"))
        self.speed_kmh_edit.setToolTip(_translate("unitConversionWidget", "Kilometres per hour"))
        self.speed_kmh_edit.setSuffix(_translate("unitConversionWidget", " km/h"))
        self.speed_kt_edit.setToolTip(_translate("unitConversionWidget", "Knots"))
        self.speed_kt_edit.setSuffix(_translate("unitConversionWidget", " kt"))
        self.groupBox.setToolTip(_translate("unitConversionWidget", "Synchronises with primary METAR station updates (temperature)"))
        self.groupBox.setTitle(_translate("unitConversionWidget", "Temperatures"))
        self.temp_C_edit.setToolTip(_translate("unitConversionWidget", "Degrees Celsius"))
        self.temp_C_edit.setSuffix(_translate("unitConversionWidget", " °C"))
        self.temp_F_edit.setToolTip(_translate("unitConversionWidget", "Degrees Fahrenheit"))
        self.temp_F_edit.setSuffix(_translate("unitConversionWidget", " °F"))
        self.groupBox_6.setToolTip(_translate("unitConversionWidget", "Synchronises with primary METAR station updates (QNH)"))
        self.groupBox_6.setTitle(_translate("unitConversionWidget", "Pressures"))
        self.pressure_inHg_edit.setToolTip(_translate("unitConversionWidget", "Inches of mercury"))
        self.pressure_inHg_edit.setSuffix(_translate("unitConversionWidget", " inHg"))
        self.pressure_hPa_edit.setToolTip(_translate("unitConversionWidget", "Hectopascals"))
        self.pressure_hPa_edit.setSuffix(_translate("unitConversionWidget", " hPa"))
        self.close_button.setText(_translate("unitConversionWidget", "Close"))

