
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weatherPane(object):
    def setupUi(self, weatherPane):
        weatherPane.setObjectName("weatherPane")
        weatherPane.resize(357, 440)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(weatherPane)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(weatherPane)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 422))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkNow_button = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.checkNow_button.setEnabled(False)
        self.checkNow_button.setObjectName("checkNow_button")
        self.gridLayout_2.addWidget(self.checkNow_button, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.selectedStationWeather_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.selectedStationWeather_groupBox.setObjectName("selectedStationWeather_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectedStationWeather_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectedStation_widget = WeatherDispWidget(self.selectedStationWeather_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedStation_widget.sizePolicy().hasHeightForWidth())
        self.selectedStation_widget.setSizePolicy(sizePolicy)
        self.selectedStation_widget.setObjectName("selectedStation_widget")
        self.verticalLayout.addWidget(self.selectedStation_widget)
        self.gridLayout_2.addWidget(self.selectedStationWeather_groupBox, 0, 0, 3, 1)
        self.setPrimaryStation_button = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.setPrimaryStation_button.setObjectName("setPrimaryStation_button")
        self.gridLayout_2.addWidget(self.setPrimaryStation_button, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.transitionLevel_info = QtWidgets.QLabel(self.groupBox)
        self.transitionLevel_info.setObjectName("transitionLevel_info")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transitionLevel_info)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.QFE_info = QtWidgets.QLabel(self.groupBox)
        self.QFE_info.setObjectName("QFE_info")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.QFE_info)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.rwyPref_info = QtWidgets.QLabel(self.groupBox)
        self.rwyPref_info.setObjectName("rwyPref_info")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rwyPref_info)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.additionalStations_tabs = QtWidgets.QTabWidget(self.groupBox_3)
        self.additionalStations_tabs.setTabsClosable(True)
        self.additionalStations_tabs.setMovable(True)
        self.additionalStations_tabs.setObjectName("additionalStations_tabs")
        self.gridLayout.addWidget(self.additionalStations_tabs, 0, 0, 2, 1)
        self.addStation_button = QtWidgets.QToolButton(self.groupBox_3)
        self.addStation_button.setObjectName("addStation_button")
        self.gridLayout.addWidget(self.addStation_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(weatherPane)
        QtCore.QMetaObject.connectSlotsByName(weatherPane)
        weatherPane.setTabOrder(self.scrollArea, self.checkNow_button)
        weatherPane.setTabOrder(self.checkNow_button, self.setPrimaryStation_button)
        weatherPane.setTabOrder(self.setPrimaryStation_button, self.additionalStations_tabs)
        weatherPane.setTabOrder(self.additionalStations_tabs, self.addStation_button)

    def retranslateUi(self, weatherPane):
        _translate = QtCore.QCoreApplication.translate
        self.checkNow_button.setText(_translate("weatherPane", "Check\n"
"now"))
        self.selectedStationWeather_groupBox.setTitle(_translate("weatherPane", "##"))
        self.setPrimaryStation_button.setToolTip(_translate("weatherPane", "Set primary station"))
        self.setPrimaryStation_button.setText(_translate("weatherPane", "Set..."))
        self.groupBox.setTitle(_translate("weatherPane", "Local analysis"))
        self.label_5.setText(_translate("weatherPane", "TL:"))
        self.transitionLevel_info.setText(_translate("weatherPane", "N/A"))
        self.label_6.setText(_translate("weatherPane", "QFE:"))
        self.QFE_info.setText(_translate("weatherPane", "N/A"))
        self.label_4.setText(_translate("weatherPane", "RWY pref.:"))
        self.rwyPref_info.setText(_translate("weatherPane", "N/A"))
        self.groupBox_3.setTitle(_translate("weatherPane", "Additional stations"))
        self.addStation_button.setToolTip(_translate("weatherPane", "Add a weather tab"))
        self.addStation_button.setText(_translate("weatherPane", "+"))

from gui.widgets.miscWidgets import WeatherDispWidget
